CREATE TABLE IF NOT EXISTS tractors (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  model VARCHAR(100) NOT NULL,
  hourly_rate DECIMAL(10,2) NOT NULL,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- helpful index
CREATE INDEX IF NOT EXISTS idx_tractors_available ON tractors (available);

