import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'ne';

type TranslationMap = Record<string, string>;

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, TranslationMap> = {
  en: {
    'brand.taglinePrimary': 'Reliable tractor rental with real-time tracking across Nepal',
    'brand.taglineSecondary': 'Secure bookings with location tracking for your peace of mind',
    'brand.subtitle': 'Secure Rental Platform',
    'nav.home': 'Home',
    'nav.platform': 'Features',
    'nav.fleet': 'Tractors',
    'nav.tractors': 'Tractors',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.privacy': 'Privacy Policy',
    'nav.insights': 'Data',
    'nav.myBookings': 'My Bookings',
    'nav.bookTractor': 'Book Tractor',
    'nav.book': 'Book',
    'nav.createAccount': 'Create Account',
    'nav.login': 'Log In',
    'nav.navigation': 'Navigation',
    'nav.profileSettings': 'Profile Settings',
    'nav.logout': 'Logout',
    'nav.customer': 'Customer',
    'nav.administrator': 'Administrator',
    'nav.languageToggle': 'नेपाली',
    'nav.adminPanel': 'Admin Panel',

    'nav.more': 'More',
    'nav.language': 'Language',
    'landing.hero.badge': 'Trusted Tractor Rental Platform',
    'landing.hero.heading': 'Rent quality tractors with real-time location tracking.',
    'landing.hero.subtitle':
      "Book tractors online with confidence. Our platform provides secure booking, real-time location tracking, and reliable service across Nepal's diverse agricultural regions.",
    'landing.hero.ctaPrimary': 'Schedule a Tractor',
    'landing.hero.ctaSecondary': 'Explore the platform',
    'landing.stats.districts.label': 'Districts covered',
    'landing.stats.districts.desc': 'From Terai to Himalayan foothills',
    'landing.stats.response.label': 'Avg. response time',
    'landing.stats.response.desc': 'Quick tractor allocation',
    'landing.stats.utilization.label': 'Fleet utilization',
    'landing.stats.utilization.desc': 'Efficient fleet management',
    'landing.dispatch.badge': 'Fleet snapshot',
    'landing.dispatch.title': 'Live Dispatch Board',
    'landing.dispatch.liveTag': 'Live Tracking',
    'landing.dispatch.loading': 'Loading dispatch data...',
    'landing.dispatch.activity.title': "Today's activity",
    'landing.dispatch.activity.body': 'High demand in Chitwan region',
    'landing.dispatch.activity.caption':
      'Multiple bookings scheduled for today. Book early to secure your preferred time slot.',
    'landing.dispatch.etaLabel': 'ETA',
    'landing.dispatch.soil.title': 'Soil compaction watch',
    'landing.dispatch.soil.badge': 'Moderate',
    'landing.dispatch.soil.body':
      'Deploy double-pass limiters in Lalitpur and Sunsari lots to protect topsoil integrity.',
    'landing.dispatch.fallback.name': 'Lamjung Valley Run',
    'landing.dispatch.fallback.location': 'Lamjung Valley',
    'landing.dispatch.fallback.distance': '42 km',
    'landing.dispatch.fallback.terrain': 'Mixed terrain',
    'landing.dispatch.fallback.eta': '18m',
    'landing.dispatch.fallback.efficiency': 'Efficiency trending ↑ 12%',
    'landing.dispatch.status.on_route': 'On route',
    'landing.dispatch.status.available': 'Available',
    'landing.dispatch.status.in_use': 'In use',
    'landing.platform.badge': 'Platform capabilities',
    'landing.platform.title': 'A command center engineered for precision agrilogistics.',
    'landing.platform.subtitle':
      'Tractor Sewa provides comprehensive fleet management for cooperatives, operators, and farm holdings. Track tractors in real time, manage bookings efficiently, and keep all records in one platform.',
    'landing.platform.cta': 'Request a guided onboarding',
    'landing.platform.features.tracking.title': 'Real-Time Tracking',
    'landing.platform.features.tracking.desc':
      'Track your booked tractor location in real-time for security and peace of mind. Know exactly where your equipment is.',
    'landing.platform.features.tracking.meta': 'GPS tracking • Location updates • Security monitoring',
    'landing.platform.features.operations.title': 'Unified Operations',
    'landing.platform.features.operations.desc':
      'One console for asset tracking, bookings, payments, and maintenance workflows—built for efficient fleet management.',
    'landing.platform.features.operations.meta': 'Digital records • Automated workflows • Analytics-ready data',
    'landing.platform.features.logistics.title': 'Smart Logistics',
    'landing.platform.features.logistics.desc':
      "Efficient dispatch and routing to minimize fuel costs and downtime. Optimized for Nepal's diverse terrain.",
    'landing.platform.features.logistics.meta': 'Route optimization • Fuel efficiency • Time management',
    'landing.platform.cards.track.title': 'Live tracking',
    'landing.platform.cards.track.body':
      'Center the map on your device and follow your hired tractor during an active booking on Live Tracking.',
    'landing.platform.cards.track.linkLabel': 'Live Tracking',
    'landing.platform.cards.catalog.title': 'Smart catalog',
    'landing.platform.cards.catalog.body':
      'Browse a dynamic fleet with real photos, fuel status, and availability on Tractors.',
    'landing.platform.cards.catalog.linkLabel': 'Tractors',
    'landing.platform.cards.admin.title': 'Admin console',
    'landing.platform.cards.admin.body':
      'Add/edit tractors, approve refunds, and audit bookings from the Admin Dashboard.',
    'landing.platform.cards.admin.linkLabel': 'Admin Dashboard',
    'landing.workflow.badge': 'Operational workflow',
    'landing.workflow.title': 'Simple booking process in three easy steps.',
    'landing.workflow.subtitle':
      'Tractor Sewa makes it easy to find, book, and track tractors. Get the equipment you need when you need it.',
    'landing.workflow.step1.title': 'Browse available tractors',
    'landing.workflow.step1.desc':
      'Search the fleet to find tractors by location, horsepower, fuel type, and availability.',
    'landing.workflow.step2.title': 'Book and confirm',
    'landing.workflow.step2.desc':
      'Select your dates and times, then confirm with secure options like eSewa or cash on delivery.',
    'landing.workflow.step3.title': 'Track and monitor',
    'landing.workflow.step3.desc': "Monitor your tractor's route and status in real time for complete transparency.",
    'landing.insights.badge': 'Insights in motion',
    'landing.insights.title': 'Operational intelligence you can act on instantly.',
    'landing.insights.subtitle':
      'Real usage data, fuel efficiency and booking trends help you route smarter and plan capacity ahead of seasonal spikes.',
    'landing.insights.highlight.satisfaction.label': 'Customer satisfaction',
    'landing.insights.highlight.satisfaction.caption': 'Based on 1,200+ bookings',
    'landing.insights.highlight.ontime.label': 'On-time delivery',
    'landing.insights.highlight.ontime.caption': 'Reliable service across all districts',
    'landing.insights.highlight.availability.label': 'Fleet availability',
    'landing.insights.highlight.availability.caption': 'High uptime and ready-to-rent status',
    'landing.insights.dashboard.title': 'Fleet Utilization Dashboard',
    'landing.insights.dashboard.card.title': 'Seasonal forecast — March window',
    'landing.insights.dashboard.card.body':
      'Expect heightened demand in Province 2 triggered by late winter rains. Activate standby tractors ahead of the second tilling cycle.',
    'landing.insights.testimonial1':
      '"The booking system is so simple and fast. We can find and book the right tractor within minutes, and the location tracking gives us peace of mind."',
    'landing.insights.testimonial2':
      '"The unified dashboard cut manual paperwork in half while improving on-time arrivals to 97%. Real-time tracking helps us manage our operations efficiently."',
    'landing.testimonial1.role': 'Cooperative Lead, Kaski',
    'landing.testimonial2.role': 'Operations Head, Himalayan Agro',
    'landing.insights.dataFreshness.title': 'Data freshness',
    'landing.insights.dataFreshness.body': 'Position and status updates every 5–15 seconds during jobs.',
    'landing.insights.privacy.title': 'Privacy & control',
    'landing.insights.privacy.body': 'Customer data encrypted in transit; admins control retention.',
    'landing.insights.exports.title': 'Exports',
    'landing.insights.exports.body': 'One-click CSV exports for bookings, tractors and analytics.',
    'landing.pricing.badge': 'Transparent pricing',
    'landing.pricing.title': 'Flexible plans aligned to your acreage reality.',
    'landing.pricing.subtitle':
      'Simple, transparent pricing with flexible booking options. Every booking includes operator verification, maintenance assurance, and digital records.',
    'landing.pricing.plan.standard.title': 'Standard Service',
    'landing.pricing.plan.standard.desc': 'Best for single-village farmers needing reliable tractors quickly.',
    'landing.pricing.plan.standard.badge': 'Core plan',
    'landing.pricing.plan.standard.feature1': '• Operator arrival target under 30 minutes',
    'landing.pricing.plan.standard.feature2': '• eSewa or cash-on-delivery settlement',
    'landing.pricing.plan.standard.feature3': '• Routine maintenance & fuel assurance',
    'landing.pricing.plan.standard.cta': 'Book Standard Plan',
    'landing.pricing.plan.premium.title': 'Premium Service',
    'landing.pricing.plan.premium.desc': 'Extra coordination for cooperatives and recurring customers.',
    'landing.pricing.plan.premium.badge': 'Full support',
    'landing.pricing.plan.premium.feature1': '• Priority dispatch & dedicated coordinator',
    'landing.pricing.plan.premium.feature2': '• Real-time tracking & fuel monitoring reports',
    'landing.pricing.plan.premium.feature3': '• Flexible billing windows & digital paperwork',
    'landing.pricing.plan.premium.cta': 'Book Premium Plan',
    'landing.fleet.badge': 'Featured Tractors',
    'landing.fleet.title': 'Featured tractors available now.',
    'landing.fleet.subtitle':
      'Every machine is location-tracked, operator-certified, and ready for your agricultural needs.',
    'landing.fleet.cta': 'View all tractors',
    'landing.sustainable.badge': 'Sustainable outcomes',
    'landing.sustainable.deskLabel': 'Sustainability desk',
    'landing.sustainable.title': 'Secure bookings with real-time location tracking for peace of mind.',
    'landing.sustainable.body':
      "Our platform provides real-time tracking to ensure security and oversight. Monitor your tractor's location throughout the rental period.",
    'landing.sustainable.stat1.title': 'Topsoil preserved',
    'landing.sustainable.stat1.body': '12,800 hectares safeguarded in 2024 season',
    'landing.sustainable.stat2.title': 'Operator compliance',
    'landing.sustainable.stat2.body': '98.6% adherence to safety and checklists',
    'landing.sustainable.quote':
      '"Tractor Sewa\'s location tracking feature gives us confidence in our operations. We can monitor equipment in real-time, ensuring security and efficient resource management."',
    'landing.sustainable.quote.author': 'Nabin Bista',
    'landing.sustainable.quote.role': 'Agronomy Director, Nepal AgroLab',
    'landing.cta.badge': 'Secure & Reliable',
    'landing.cta.title': 'Ready to book your next tractor rental?',
    'landing.cta.subtitle':
      'Join farmers and cooperatives using Tractor Sewa to access quality tractors with real-time tracking.',
    'landing.cta.primary': 'Get Started Today',
    'landing.cta.secondary': 'Log in to your console',
    'landing.footer.tagline': 'Reliable tractor rental platform for Nepal',
    'landing.footer.copy': '© 2025 Tractor Sewa. Secure tractor rental services across Nepal.',
    'landing.dispatch.fallback.destination': 'Destination not assigned',
    'landing.dispatch.dynamicTerrain': 'Mixed terrain',
    'landing.dispatch.etaFallback': '—',
    'landing.dispatch.fallback.efficiency': 'Efficiency trending ↑ 12%',
    'status.available': 'Available',
    'status.unavailable': 'Unavailable',
    'status.booked': 'Booked',
    'status.in_use': 'In Use',
    'tractors.header.title': 'Browse Tractors',
    'tractors.header.subtitle': 'Find available and in-use tractors in your area',
    'tractors.filters.toggle.hide': 'Hide Filters',
    'tractors.filters.toggle.show': 'Advanced Filters',
    'tractors.filters.types': 'Tractor Types',
    'tractors.filters.type.compact': 'Compact',
    'tractors.filters.type.row': 'Row Crop',
    'tractors.filters.type.speciality': 'Specialty',
    'tractors.filters.type.utility': 'Utility',
    'tractors.filters.type.orchard': 'Orchard',
    'tractors.filters.price': 'Price Range',
    'tractors.filters.hp': 'Horsepower',
    'tractors.filters.search': 'Search tractors...',
    'tractors.filters.location': 'Location',
    'tractors.filters.location.all': 'All Locations',
    'tractors.filters.availability': 'Availability',
    'tractors.filters.availability.all': 'All Status',
    'tractors.filters.availability.available': 'Available',
    'tractors.filters.availability.unavailable': 'Unavailable',
    'tractors.filters.rating': 'Minimum Rating',
    'tractors.filters.rating.any': 'Any Rating',
    'tractors.filters.action.cancel': 'Reset',
    'tractors.filters.action.apply': 'Apply Filters',
    'tractors.loading': 'Loading tractors...',
    'tractors.error': 'Failed to load tractors',
    'tractors.showing': 'Showing',
    'tractors.showing.unit': 'tractors',
    'tractors.showing.unit.single': 'tractor',
    'tractors.power': 'Power',
    'tractors.bookings': 'Bookings',
    'tractors.fuelLevel': 'Fuel Level',
    'tractors.fuelUnavailable': 'Fuel data unavailable',
    'tractors.location': 'Location not specified',
    'tractors.nextAvailable': 'Next Available',
    'tractors.pricePerHour': 'per hour',
    'tractors.bookNow': 'Book Now',
    'tractors.unavailable': 'Unavailable',
    'tractors.empty.title': 'No tractors found',
    'tractors.empty.subtitle': 'Try adjusting your filters',
    'tractors.dialog.title': 'Tractor Availability',
    'tractors.dialog.subtitle': 'Detailed status & next availability',
    'tractors.dialog.currentStatus': 'Current Status',
    'tractors.dialog.nextAvailable': 'Next Available',
    'tractors.dialog.currentLocation': 'Current Location',
    'tractors.dialog.messageUnavailable':
      'This tractor is unavailable right now. Please select another tractor or check back soon.',
    'tractors.dialog.close': 'Close',
    'tractors.dialog.notScheduled': 'Not scheduled',
    'tractors.dialog.locationNotSpecified': 'Not specified',
    'tractors.dialog.statusMessage': '{name} is currently {status}. Once the existing booking wraps up, it will be ready again for a new delivery.',
    'tractors.dialog.defaultMessage': 'This tractor is unavailable right now. Please select another tractor or check back soon.',
    'tractors.card.nextAvailableLabel': 'Next Available:',
  },
  ne: {
    'brand.taglinePrimary': 'रियल-टाइम ट्र्याकिङ सहितको भरपर्दो ट्र्याक्टर भाडा सेवा',
    'brand.taglineSecondary': 'स्थान ट्र्याकिङसहित सुरक्षित बुकिङ अब सहज',
    'brand.subtitle': 'सुरक्षित भाडा प्लेटफर्म',
    'nav.home': 'गृहपृष्ठ',
    'nav.platform': 'प्लेटफर्म',
    'nav.fleet': 'फ्लीट',
    'nav.tractors': 'ट्र्याक्टरहरू',
    'nav.about': 'हाम्रो बारेमा',
    'nav.contact': 'सम्पर्क',
    'nav.privacy': 'गोपनीयता नीति',
    'nav.insights': 'अन्तर्दृष्टि',
    'nav.myBookings': 'मेरो बुकिङ',
    'nav.bookTractor': 'ट्र्याक्टर बुक',
    'nav.book': 'बुक',
    'nav.createAccount': 'खाता बनाउनुहोस्',
    'nav.login': 'लगइन',
    'nav.navigation': 'नेभिगेसन',
    'nav.profileSettings': 'प्रोफाइल सेटिङ',
    'nav.logout': 'लगआउट',
    'nav.customer': 'ग्राहक',
    'nav.administrator': 'प्रशासक',
    'nav.languageToggle': 'English',
    'nav.adminPanel': 'एडमिन प्यानल',
    'nav.more': 'थप',
    'nav.language': 'भाषा',
    'landing.hero.badge': 'विश्वसनीय ट्र्याक्टर भाडा प्लेटफर्म',
    'landing.hero.heading': 'रियल-टाइम लोकेशन ट्र्याकिङसहित गुणस्तरीय ट्र्याक्टर भाडामा लिऔँ।',
    'landing.hero.subtitle':
      'हाम्रो प्लेटफर्मबाट निश्चिन्त भएर ट्र्याक्टर बुक गर्नुहोस्। सुरक्षित बुकिङ, रियल-टाइम लोकेशन ट्र्याकिङ, र नेपालका सबै भू-भागमा भरपर्दो सेवा।',
    'landing.hero.ctaPrimary': 'ट्र्याक्टर शेड्युल गर्नुहोस्',
    'landing.hero.ctaSecondary': 'प्लेटफर्म हेर्नुहोस्',
    'landing.stats.districts.label': 'कभर भएका जिल्ला',
    'landing.stats.districts.desc': 'तराईदेखि हिमाली भेगसम्म',
    'landing.stats.response.label': 'औसत प्रतिक्रिया समय',
    'landing.stats.response.desc': 'छिटो ट्र्याक्टर अभिरचना',
    'landing.stats.utilization.label': 'फ्लीट उपयोग',
    'landing.stats.utilization.desc': 'उत्पादक फ्लीट व्यवस्थापन',
    'landing.dispatch.badge': 'फ्लीट स्न्यापशट',
    'landing.dispatch.title': 'लाईभ डिस्प्याच बोर्ड',
    'landing.dispatch.liveTag': 'लाईभ ट्र्याकिङ',
    'landing.dispatch.loading': 'डिस्प्याच डेटा लोड भइरहेकाे छ...',
    'landing.dispatch.activity.title': 'आजको गतिविधि',
    'landing.dispatch.activity.body': 'चितवन क्षेत्रमा उच्च माग',
    'landing.dispatch.activity.caption': 'आज धेरै बुकिङ छन्। मनपर्ने समय सुरक्षित गर्न अग्रिम बुक गर्नुहोस्।',
    'landing.dispatch.etaLabel': 'अनुमानित समय',
    'landing.dispatch.soil.title': 'माटो संरक्षण अलर्ट',
    'landing.dispatch.soil.badge': 'मध्यम',
    'landing.dispatch.soil.body': 'ललितपुर र Sunsari मा दोहोरो पास लिमिटर प्रयोग गरेर माथिल्लो माटो जोगाउनुहोस्।',
    'landing.dispatch.fallback.name': 'लमजुङ भ्याली रन',
    'landing.dispatch.fallback.location': 'लमजुङ भ्याली',
    'landing.dispatch.fallback.distance': '४२ किमी',
    'landing.dispatch.fallback.terrain': 'मिश्रित भू-भाग',
    'landing.dispatch.fallback.eta': '१८ मिनेट',
    'landing.dispatch.fallback.efficiency': 'दक्षता १२% माथि',
    'landing.dispatch.status.on_route': 'मार्गमा',
    'landing.dispatch.status.available': 'उपलब्ध',
    'landing.dispatch.status.in_use': 'प्रयोगमा',
    'landing.platform.badge': 'प्लेटफर्म क्षमताहरू',
    'landing.platform.title': 'कृषि-लोजिस्टिक्सका लागि निर्माण गरिएको नियन्त्रण केन्द्र।',
    'landing.platform.subtitle':
      'Tractor Sewa ले सहकारी, अपरेटर र फार्म होल्डिङका लागि पूर्ण फ्लीट व्यवस्थापन प्रदान गर्दछ। रियल-टाइम ट्र्याकिङ, बुकिङ रेकर्ड र मर्मत सबै एक ठाउँमा।',
    'landing.platform.cta': 'गाइडेड अनबोर्डिङ माग्नुहोस्',
    'landing.platform.features.tracking.title': 'रियल-टाइम ट्र्याकिङ',
    'landing.platform.features.tracking.desc':
      'सुरक्षाका लागि ट्र्याक्टरको स्थान निरन्तर हेर्नुहोस्। उपकरण कुन ठाउँमा छ, सधैं थाहा हुन्छ।',
    'landing.platform.features.tracking.meta': 'GPS ट्र्याकिङ • लोकेशन अपडेट • सुरक्षा निगरानी',
    'landing.platform.features.operations.title': 'एकीकृत अपरेसन',
    'landing.platform.features.operations.desc':
      'एसेट ट्र्याकिङ, बुकिङ, भुक्तानी र मर्मतका सबै वर्कफ्लो एकै कनसोलमा— फ्लीट व्यवस्थापनलाई सहज बनाउँदै।',
    'landing.platform.features.operations.meta': 'डिजिटल रेकर्ड • स्वचालित वर्कफ्लो • विश्लेषण-तयार डेटा',
    'landing.platform.features.logistics.title': 'स्मार्ट लोजिस्टिक्स',
    'landing.platform.features.logistics.desc':
      'इन्धन लागत र डाउनटाइम घटाउन दक्ष डिस्प्याच र रुटिङ। नेपालको विविध भू-भागका लागि अनुकूल।',
    'landing.platform.features.logistics.meta': 'रुट अनुकूलन • इन्धन दक्षता • समय व्यवस्थापन',
    'landing.platform.cards.track.title': 'लाईभ ट्र्याकिङ',
    'landing.platform.cards.track.body':
      'सक्रिय बुकिङको क्रममा नक्शामा आफ्नाे उपकरण पछ्याउन Live Tracking मा जाऔँ।',
    'landing.platform.cards.track.linkLabel': 'Live Tracking',
    'landing.platform.cards.catalog.title': 'स्मार्ट क्याटलग',
    'landing.platform.cards.catalog.body':
      'रियल फोटो, इन्धन स्थिति र उपलब्धतासहित ट्र्याक्टर सूची Tractors पेजमा हेर्नुहोस्।',
    'landing.platform.cards.catalog.linkLabel': 'Tractors',
    'landing.platform.cards.admin.title': 'एडमिन कन्सोल',
    'landing.platform.cards.admin.body':
      'ट्र्याक्टर थप/सम्पादन, रिफन्ड स्वीकृति र अडिट कार्य Admin Dashboard बाट व्यवस्थापन गर्नुहोस्।',
    'landing.platform.cards.admin.linkLabel': 'Admin Dashboard',
    'landing.workflow.badge': 'अपरेशनल वर्कफ्लो',
    'landing.workflow.title': 'तीन सरल चरणमा बुकिङ प्रक्रिया।',
    'landing.workflow.subtitle':
      'Tractor Sewa ले ट्र्याक्टर खोज्न, बुक गर्न र ट्र्याकिङ गर्न सजिलो बनाउँछ। समयमै उपकरण पाउनुहोस्।',
    'landing.workflow.step1.title': 'उपलब्ध ट्र्याक्टर हेर्नुहोस्',
    'landing.workflow.step1.desc':
      'स्थान, पावर र उपलब्धताको आधारमा फिल्टर गरेर आफ्नो फ्लीट छान्नुहोस्।',
    'landing.workflow.step2.title': 'बुक र पुष्टि गर्नुहोस्',
    'landing.workflow.step2.desc':
      'मिति/समय छानेपछि eSewa वा COD जस्ता सुरक्षित विकल्पबाट पुष्टि गर्नुहोस्।',
    'landing.workflow.step3.title': 'ट्र्याक र निगरानी',
    'landing.workflow.step3.desc': 'बुक गरिएको ट्र्याक्टरको मार्ग र स्थिति रियल-टाइम ट्र्याकिङमा हेर्नुहोस्।',
    'landing.insights.badge': 'गतिमा अन्तर्दृष्टि',
    'landing.insights.title': 'तुरुन्त प्रयोग गर्न मिल्ने अपरेशनल बुद्धिमत्ता।',
    'landing.insights.subtitle':
      'वास्तविक प्रयोग, इन्धन दक्षता र बुकिङ ट्रेन्डले रुट योजना र क्षमताको पूर्वतयारीमा मद्दत गर्छ।',
    'landing.insights.highlight.satisfaction.label': 'ग्राहक सन्तुष्टि',
    'landing.insights.highlight.satisfaction.caption': '१,२००+ बुकिङको आधारमा',
    'landing.insights.highlight.ontime.label': 'समयमै डेलिभरी',
    'landing.insights.highlight.ontime.caption': 'सबै जिल्लामा भरपर्दो सेवा',
    'landing.insights.highlight.availability.label': 'फ्लीट उपलब्धता',
    'landing.insights.highlight.availability.caption': 'उच्च अपटाइम र तत्पर अवस्था',
    'landing.insights.dashboard.title': 'फ्लीट उपयोग ड्यासबोर्ड',
    'landing.insights.dashboard.card.title': 'मौसमी पूर्वानुमान — फागुन झ्याल',
    'landing.insights.dashboard.card.body':
      'प्रदेश २ मा वर्षात्को कारण माग बढ्ने अपेक्षा। दोश्रो जोत्नुअघि जनकपुर र वीरगञ्जमा स्ट्यान्डबाइ ट्र्याक्टर सक्रिय गर्नुहोस्।',
    'landing.insights.testimonial1':
      '"बुकिङ प्रणाली अत्यन्त सरल र छिटो छ। केही मिनेटमै चाहिएको ट्र्याक्टर पाउछौँ, र ट्र्याकिङले थप विश्वास दिलाउँछ।"',
    'landing.insights.testimonial2':
      '"एकीकृत ड्यासबोर्डले कागजी झन्झट ५०%ले घटायो र ९७% समयमै डेलिभरी सम्भव बनायो। रियल-टाइम ट्र्याकिङले सञ्चालन व्यवस्थित हुन्छ।"',
    'landing.testimonial1.role': 'कास्की, सहकारी प्रमुख',
    'landing.testimonial2.role': 'हिमालयन एग्रो, सञ्चालन प्रमुख',
    'landing.insights.dataFreshness.title': 'डेटा ताजा स्थिति',
    'landing.insights.dataFreshness.body': 'कामका क्रममा ५–१५ सेकेन्डको अन्तरमा स्थिति अपडेट।',
    'landing.insights.privacy.title': 'गोपनीयता र नियन्त्रण',
    'landing.insights.privacy.body': 'डाटा ट्रान्जिटमा इन्क्रिप्टेड, सञ्चयन अवधि एडमिनले तय गर्छ।',
    'landing.insights.exports.title': 'एक्सपोर्ट',
    'landing.insights.exports.body': 'बुकिङ, ट्र्याक्टर र एनालिटिक्सका लागि एक-क्लिक CSV एक्सपोर्ट।',
    'landing.pricing.badge': 'पारदर्शी मूल्य',
    'landing.pricing.title': 'आप्नो उत्पादन क्षेत्रसँग मिल्ने लचिलो योजना।',
    'landing.pricing.subtitle':
      'सरल र स्पष्ट मूल्य, प्रत्येक बुकिङमा अपरेटर प्रमाणीकरण, मर्मत आश्वासन र डिजिटल अभिलेख समावेश।',
    'landing.pricing.plan.standard.title': 'मानक सेवा',
    'landing.pricing.plan.standard.desc': 'छोटो समुदाय वा किसान समूहका लागि छिटो र भरपर्दो सेवा।',
    'landing.pricing.plan.standard.badge': 'मूल योजना',
    'landing.pricing.plan.standard.feature1': '• ३० मिनेटभित्र अपरेटर पठाउने लक्ष्य',
    'landing.pricing.plan.standard.feature2': '• eSewa वा नगद भुक्तानीका विकल्प',
    'landing.pricing.plan.standard.feature3': '• रूटीन मर्मत र इन्धन आश्वासन',
    'landing.pricing.plan.standard.cta': 'मानक योजना बुक गर्नुहोस्',
    'landing.pricing.plan.premium.title': 'प्रिमियम सेवा',
    'landing.pricing.plan.premium.desc': 'सहकारी तथा पुनरावर्ती ग्राहकका लागि थप समन्वय।',
    'landing.pricing.plan.premium.badge': 'पूर्ण सहयोग',
    'landing.pricing.plan.premium.feature1': '• प्राथमिकता डिस्प्याच र समर्पित समन्वयकर्ता',
    'landing.pricing.plan.premium.feature2': '• रियल-टाइम ट्र्याकिङ र इन्धन रिपोर्ट',
    'landing.pricing.plan.premium.feature3': '• लचिलो बिलिङ र डिजिटल कागजात',
    'landing.pricing.plan.premium.cta': 'प्रिमियम योजना बुक गर्नुहोस्',
    'landing.fleet.badge': 'विशेष ट्र्याक्टरहरू',
    'landing.fleet.title': 'अहिले उपलब्ध प्रमुख ट्र्याक्टरहरू।',
    'landing.fleet.subtitle':
      'प्रत्येक मेसिन स्थान-ट्र्याक, अपरेटर प्रमाणीकरण र तपाईंको आवश्यकता अनुसार तयार।',
    'landing.fleet.cta': 'सबै ट्र्याक्टरहरू हेर्नुहोस्',
    'landing.sustainable.badge': 'टिकाउ नतिजा',
    'landing.sustainable.deskLabel': 'दिगोपन डेस्क',
    'landing.sustainable.title': 'शान्तिका लागि रियल-टाइम लोकेशनसहित सुरक्षित बुकिङ।',
    'landing.sustainable.body':
      'हाम्रो प्लेटफर्मले सुरक्षा र सञ्चालन निगरानीका लागि रियल-टाइम ट्र्याकिङ प्रदान गर्छ। Tractor Sewa बाट भाडाको अवधिभर ट्र्याक्टरको लोकेशन हेर्नुस्।',
    'landing.sustainable.stat1.title': 'माथिल्लो माटो जोगियो',
    'landing.sustainable.stat1.body': '२०२४ मा १२,८०० हे. कृषि भूमि सुरक्षित',
    'landing.sustainable.stat2.title': 'अपरेटर अनुपालन',
    'landing.sustainable.stat2.body': 'सुरक्षा तथा चेकलिस्टमा ९८.६% पालना',
    'landing.sustainable.quote':
      '"Tractor Sewa को लोकेशन ट्र्याकिङले हामीलाई सञ्चालनमा भरपर्दो बनायो। वास्तविक-समय अनुगमनले सुरक्षा र स्रोत व्यवस्थापनमा आत्मविश्वास दिन्छ।"',
    'landing.sustainable.quote.author': 'नवीन बिष्ट',
    'landing.sustainable.quote.role': 'एग्रोनोमी निर्देशक, नेपाल एग्रोल्याब',
    'landing.cta.badge': 'सुरक्षित र भरपर्दो',
    'landing.cta.title': 'के तपाईं अर्को ट्र्याक्टर भाडा लिन तयार हुनुहुन्छ?',
    'landing.cta.subtitle':
      'Tractor Sewa प्रयोग गर्ने किसान र सहकारीसँगै जडान हुनुहोस्, रियल-टाइम ट्र्याकिङसहित गुणवत्तापूर्ण सेवा पाउनुहोस्।',
    'landing.cta.primary': 'आजै सुरु गर्नुहोस्',
    'landing.cta.secondary': 'कन्सोलमा लगइन गर्नुहोस्',
    'landing.footer.tagline': 'नेपालका लागि भरपर्दो ट्र्याक्टर भाडा प्लेटफर्म',
    'landing.footer.copy': '© २०२५ Tractor Sewa। नेपालभर सुरक्षित ट्र्याक्टर भाडा सेवा।',
    'landing.dispatch.fallback.destination': 'गन्तव्य तोकिएको छैन',
    'landing.dispatch.dynamicTerrain': 'मिश्रित भूभाग',
    'landing.dispatch.etaFallback': '—',
    'landing.dispatch.fallback.efficiency': 'दक्षता १२% माथि',
    'status.available': 'उपलब्ध',
    'status.unavailable': 'अनुपलब्ध',
    'status.booked': 'बुक भएको',
    'status.in_use': 'प्रयोगमा',
    'tractors.header.title': 'उपलब्ध ट्र्याक्टरहरू हेर्नुहोस्',
    'tractors.header.subtitle': 'आफ्नो क्षेत्रमा उपलब्ध र प्रयोगमा रहेका ट्र्याक्टर खोज्नुहोस्',
    'tractors.filters.toggle.hide': 'फिल्टर लुकाउनुहोस्',
    'tractors.filters.toggle.show': 'उन्नत फिल्टर',
    'tractors.filters.types': 'ट्र्याक्टर प्रकार',
    'tractors.filters.type.compact': 'कम्प्याक्ट',
    'tractors.filters.type.row': 'रो क्रप',
    'tractors.filters.type.speciality': 'विशेष',
    'tractors.filters.type.utility': 'युटिलिटी',
    'tractors.filters.type.orchard': 'अर्चर्ड',
    'tractors.filters.price': 'मूल्य दायरा',
    'tractors.filters.hp': 'हर्सपावर',
    'tractors.filters.search': 'ट्र्याक्टर खोज्नुहोस्...',
    'tractors.filters.location': 'स्थान',
    'tractors.filters.location.all': 'सबै स्थान',
    'tractors.filters.availability': 'उपलब्धता',
    'tractors.filters.availability.all': 'सबै स्थिति',
    'tractors.filters.availability.available': 'उपलब्ध',
    'tractors.filters.availability.unavailable': 'अनुपलब्ध',
    'tractors.filters.rating': 'न्यूनतम रेटिङ',
    'tractors.filters.rating.any': 'कुनै पनि रेटिङ',
    'tractors.filters.action.cancel': 'रिसेट',
    'tractors.filters.action.apply': 'फिल्टर लागू गर्नुहोस्',
    'tractors.loading': 'ट्र्याक्टरहरू लोड भइरहेको छ...',
    'tractors.error': 'ट्र्याक्टर लोड गर्न असफल',
    'tractors.showing': 'कुल',
    'tractors.showing.unit': 'ट्र्याक्टर',
    'tractors.showing.unit.single': 'ट्र्याक्टर',
    'tractors.power': 'पावर',
    'tractors.bookings': 'बुकिङ',
    'tractors.fuelLevel': 'इन्धन स्तर',
    'tractors.fuelUnavailable': 'इन्धन जानकारी उपलब्ध छैन',
    'tractors.location': 'स्थान निर्दिष्ट गरिएको छैन',
    'tractors.nextAvailable': 'अर्को उपलब्ध समय',
    'tractors.pricePerHour': 'प्रति घण्टा',
    'tractors.bookNow': 'बुक गर्नुहोस्',
    'tractors.unavailable': 'अनुपलब्ध',
    'tractors.empty.title': 'ट्र्याक्टर फेला परेन',
    'tractors.empty.subtitle': 'कृपया फिल्टर परिवर्तन गरेर पुन: प्रयास गर्नुहोस्',
    'tractors.dialog.title': 'ट्र्याक्टर उपलब्धता',
    'tractors.dialog.subtitle': 'विस्तृत स्थिति र आगामी उपलब्धता',
    'tractors.dialog.currentStatus': 'वर्तमान स्थिति',
    'tractors.dialog.nextAvailable': 'अर्को उपलब्ध समय',
    'tractors.dialog.currentLocation': 'हालको स्थान',
    'tractors.dialog.messageUnavailable':
      'यो ट्र्याक्टर अहिले उपलब्ध छैन। कृपया अर्को ट्र्याक्टर छान्नुहोस् वा पछि पुन: प्रयास गर्नुहोस्।',
    'tractors.dialog.close': 'बन्द गर्नुहोस्',
    'tractors.dialog.notScheduled': 'निर्धारण गरिएको छैन',
    'tractors.dialog.locationNotSpecified': 'निश्चित गरिएको छैन',
    'tractors.dialog.statusMessage': '{name} अहिले {status} अवस्थामा छ। यो बुकिङ पूरा भएपछि तुरुन्त अर्को वितरणका लागि तयार हुनेछ।',
    'tractors.dialog.defaultMessage': 'यो ट्र्याक्टर हाल उपलब्ध छैन। कृपया अर्को ट्र्याक्टर छान्नुहोस् वा पछि फेरि प्रयास गर्नुहोस्।',
    'tractors.card.nextAvailableLabel': 'अर्को उपलब्ध:',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('tbs-language') as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('tbs-language', language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string) => {
      const dictionary = translations[language];
      return dictionary[key] || translations.en[key] || key;
    };

    const toggleLanguage = () => {
      setLanguage(prev => (prev === 'en' ? 'ne' : 'en'));
    };

    return {
      language,
      setLanguage,
      toggleLanguage,
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
