import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'ne';

type TranslationMap = Record<string, string>;

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, TranslationMap> = {
  en: {
    'brand.taglinePrimary': 'Reliable tractor rental with real-time tracking across Nepal',
    'brand.taglineSecondary': 'Secure bookings with location tracking for your peace of mind',
    'brand.subtitle': 'Secure Rental Platform',
    'nav.home': 'Home',
    'nav.platform': 'Features',
    'nav.fleet': 'Tractors',
    'nav.tractors': 'Tractors',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.privacy': 'Privacy Policy',
    'nav.insights': 'Data',
    'nav.myBookings': 'My Bookings',
    'nav.bookTractor': 'Book Tractor',
    'nav.book': 'Book',
    'nav.createAccount': 'Create Account',
    'nav.login': 'Log In',
    'nav.navigation': 'Navigation',
    'nav.profileSettings': 'Profile Settings',
    'nav.logout': 'Logout',
    'nav.customer': 'Customer',
    'nav.administrator': 'Administrator',
    'nav.languageToggle': 'नेपाली',
    'nav.adminPanel': 'Admin Panel',

    'nav.more': 'More',
    'nav.language': 'Language',
    'landing.hero.badge': 'Trusted Tractor Rental Platform',
    'landing.hero.heading': 'Rent quality tractors with real-time location tracking.',
    'landing.hero.subtitle':
      "Book tractors online with confidence. Our platform provides secure booking, real-time location tracking, and reliable service across Nepal's diverse agricultural regions.",
    'landing.hero.ctaPrimary': 'Schedule a Tractor',
    'landing.hero.ctaSecondary': 'Explore the platform',
    'landing.stats.districts.label': 'Districts covered',
    'landing.stats.districts.desc': 'From Terai to Himalayan foothills',
    'landing.stats.response.label': 'Avg. response time',
    'landing.stats.response.desc': 'Quick tractor allocation',
    'landing.stats.utilization.label': 'Fleet utilization',
    'landing.stats.utilization.desc': 'Efficient fleet management',
    'landing.dispatch.badge': 'Fleet snapshot',
    'landing.dispatch.title': 'Live Dispatch Board',
    'landing.dispatch.liveTag': 'Live Tracking',
    'landing.dispatch.loading': 'Loading dispatch data...',
    'landing.dispatch.activity.title': "Today's activity",
    'landing.dispatch.activity.body': 'High demand in Chitwan region',
    'landing.dispatch.activity.caption':
      'Multiple bookings scheduled for today. Book early to secure your preferred time slot.',
    'landing.dispatch.etaLabel': 'ETA',
    'landing.dispatch.soil.title': 'Soil compaction watch',
    'landing.dispatch.soil.badge': 'Moderate',
    'landing.dispatch.soil.body':
      'Deploy double-pass limiters in Lalitpur and Sunsari lots to protect topsoil integrity.',
    'landing.dispatch.fallback.name': 'Lamjung Valley Run',
    'landing.dispatch.fallback.location': 'Lamjung Valley',
    'landing.dispatch.fallback.distance': '42 km',
    'landing.dispatch.fallback.terrain': 'Mixed terrain',
    'landing.dispatch.fallback.eta': '18m',
    'landing.dispatch.fallback.efficiency': 'Efficiency trending ↑ 12%',
    'landing.dispatch.status.on_route': 'On route',
    'landing.dispatch.status.available': 'Available',
    'landing.dispatch.status.in_use': 'In use',
    'landing.platform.badge': 'Platform capabilities',
    'landing.platform.title': 'A command center engineered for precision agrilogistics.',
    'landing.platform.subtitle':
      'Tractor Sewa provides comprehensive fleet management for cooperatives, operators, and farm holdings. Track tractors in real time, manage bookings efficiently, and keep all records in one platform.',
    'landing.platform.cta': 'Request a guided onboarding',
    'landing.platform.features.tracking.title': 'Real-Time Tracking',
    'landing.platform.features.tracking.desc':
      'Track your booked tractor location in real-time for security and peace of mind. Know exactly where your equipment is.',
    'landing.platform.features.tracking.meta': 'GPS tracking • Location updates • Security monitoring',
    'landing.platform.features.operations.title': 'Unified Operations',
    'landing.platform.features.operations.desc':
      'One console for asset tracking, bookings, payments, and maintenance workflows—built for efficient fleet management.',
    'landing.platform.features.operations.meta': 'Digital records • Automated workflows • Analytics-ready data',
    'landing.platform.features.logistics.title': 'Smart Logistics',
    'landing.platform.features.logistics.desc':
      "Efficient dispatch and routing to minimize fuel costs and downtime. Optimized for Nepal's diverse terrain.",
    'landing.platform.features.logistics.meta': 'Route optimization • Fuel efficiency • Time management',
    'landing.platform.cards.track.title': 'Live tracking',
    'landing.platform.cards.track.body':
      'Center the map on your device and follow your hired tractor during an active booking on Live Tracking.',
    'landing.platform.cards.track.linkLabel': 'Live Tracking',
    'landing.platform.cards.catalog.title': 'Smart catalog',
    'landing.platform.cards.catalog.body':
      'Browse a dynamic fleet with real photos, fuel status, and availability on Tractors.',
    'landing.platform.cards.catalog.linkLabel': 'Tractors',
    'landing.platform.cards.admin.title': 'Admin console',
    'landing.platform.cards.admin.body':
      'Add/edit tractors, approve refunds, and audit bookings from the Admin Dashboard.',
    'landing.platform.cards.admin.linkLabel': 'Admin Dashboard',
    'landing.workflow.badge': 'Operational workflow',
    'landing.workflow.title': 'Simple booking process in three easy steps.',
    'landing.workflow.subtitle':
      'Tractor Sewa makes it easy to find, book, and track tractors. Get the equipment you need when you need it.',
    'landing.workflow.step1.title': 'Browse available tractors',
    'landing.workflow.step1.desc':
      'Search the fleet to find tractors by location, horsepower, fuel type, and availability.',
    'landing.workflow.step2.title': 'Book and confirm',
    'landing.workflow.step2.desc':
      'Select your dates and times, then confirm with secure options like eSewa or cash on delivery.',
    'landing.workflow.step3.title': 'Track and monitor',
    'landing.workflow.step3.desc': "Monitor your tractor's route and status in real time for complete transparency.",
    'landing.insights.badge': 'Insights in motion',
    'landing.insights.title': 'Operational intelligence you can act on instantly.',
    'landing.insights.subtitle':
      'Real usage data, fuel efficiency and booking trends help you route smarter and plan capacity ahead of seasonal spikes.',
    'landing.insights.highlight.satisfaction.label': 'Customer satisfaction',
    'landing.insights.highlight.satisfaction.caption': 'Based on 1,200+ bookings',
    'landing.insights.highlight.ontime.label': 'On-time delivery',
    'landing.insights.highlight.ontime.caption': 'Reliable service across all districts',
    'landing.insights.highlight.availability.label': 'Fleet availability',
    'landing.insights.highlight.availability.caption': 'High uptime and ready-to-rent status',
    'landing.insights.dashboard.title': 'Fleet Utilization Dashboard',
    'landing.insights.dashboard.card.title': 'Seasonal forecast — March window',
    'landing.insights.dashboard.card.body':
      'Expect heightened demand in Province 2 triggered by late winter rains. Activate standby tractors ahead of the second tilling cycle.',
    'landing.insights.testimonial1':
      '"The booking system is so simple and fast. We can find and book the right tractor within minutes, and the location tracking gives us peace of mind."',
    'landing.insights.testimonial2':
      '"The unified dashboard cut manual paperwork in half while improving on-time arrivals to 97%. Real-time tracking helps us manage our operations efficiently."',
    'landing.testimonial1.role': 'Cooperative Lead, Kaski',
    'landing.testimonial2.role': 'Operations Head, Himalayan Agro',
    'landing.insights.dataFreshness.title': 'Data freshness',
    'landing.insights.dataFreshness.body': 'Position and status updates every 5–15 seconds during jobs.',
    'landing.insights.privacy.title': 'Privacy & control',
    'landing.insights.privacy.body': 'Customer data encrypted in transit; admins control retention.',
    'landing.insights.exports.title': 'Exports',
    'landing.insights.exports.body': 'One-click CSV exports for bookings, tractors and analytics.',
    'landing.pricing.badge': 'Transparent pricing',
    'landing.pricing.title': 'Flexible plans aligned to your acreage reality.',
    'landing.pricing.subtitle':
      'Simple, transparent pricing with flexible booking options. Every booking includes operator verification, maintenance assurance, and digital records.',
    'landing.pricing.plan.standard.title': 'Standard Service',
    'landing.pricing.plan.standard.desc': 'Best for single-village farmers needing reliable tractors quickly.',
    'landing.pricing.plan.standard.badge': 'Core plan',
    'landing.pricing.plan.standard.feature1': '• Operator arrival target under 30 minutes',
    'landing.pricing.plan.standard.feature2': '• eSewa or cash-on-delivery settlement',
    'landing.pricing.plan.standard.feature3': '• Routine maintenance & fuel assurance',
    'landing.pricing.plan.standard.cta': 'Book Standard Plan',
    'landing.pricing.plan.premium.title': 'Premium Service',
    'landing.pricing.plan.premium.desc': 'Extra coordination for cooperatives and recurring customers.',
    'landing.pricing.plan.premium.badge': 'Full support',
    'landing.pricing.plan.premium.feature1': '• Priority dispatch & dedicated coordinator',
    'landing.pricing.plan.premium.feature2': '• Real-time tracking & fuel monitoring reports',
    'landing.pricing.plan.premium.feature3': '• Flexible billing windows & digital paperwork',
    'landing.pricing.plan.premium.cta': 'Book Premium Plan',
    'landing.fleet.badge': 'Featured Tractors',
    'landing.fleet.title': 'Featured tractors available now.',
    'landing.fleet.subtitle':
      'Every machine is location-tracked, operator-certified, and ready for your agricultural needs.',
    'landing.fleet.cta': 'View all tractors',
    'landing.sustainable.badge': 'Sustainable outcomes',
    'landing.sustainable.deskLabel': 'Sustainability desk',
    'landing.sustainable.title': 'Secure bookings with real-time location tracking for peace of mind.',
    'landing.sustainable.body':
      "Our platform provides real-time tracking to ensure security and oversight. Monitor your tractor's location throughout the rental period.",
    'landing.sustainable.stat1.title': 'Topsoil preserved',
    'landing.sustainable.stat1.body': '12,800 hectares safeguarded in 2024 season',
    'landing.sustainable.stat2.title': 'Operator compliance',
    'landing.sustainable.stat2.body': '98.6% adherence to safety and checklists',
    'landing.sustainable.quote':
      '"Tractor Sewa\'s location tracking feature gives us confidence in our operations. We can monitor equipment in real-time, ensuring security and efficient resource management."',
    'landing.sustainable.quote.author': 'Nabin Bista',
    'landing.sustainable.quote.role': 'Agronomy Director, Nepal AgroLab',
    'landing.cta.badge': 'Secure & Reliable',
    'landing.cta.title': 'Ready to book your next tractor rental?',
    'landing.cta.subtitle':
      'Join farmers and cooperatives using Tractor Sewa to access quality tractors with real-time tracking.',
    'landing.cta.primary': 'Get Started Today',
    'landing.cta.secondary': 'Log in to your console',
    'landing.footer.tagline': 'Reliable tractor rental platform for Nepal',
    'landing.footer.copy': '© 2025 Tractor Sewa. Secure tractor rental services across Nepal.',
    'landing.dispatch.fallback.destination': 'Destination not assigned',
    'landing.dispatch.dynamicTerrain': 'Mixed terrain',
    'landing.dispatch.etaFallback': '—',
    'landing.dispatch.fallback.efficiency': 'Efficiency trending ↑ 12%',
    'status.available': 'Available',
    'status.unavailable': 'Unavailable',
    'status.booked': 'Booked',
    'status.in_use': 'In Use',
    'tractors.header.title': 'Browse Tractors',
    'tractors.header.subtitle': 'Find available and in-use tractors in your area',
    'tractors.filters.toggle.hide': 'Hide Filters',
    'tractors.filters.toggle.show': 'Advanced Filters',
    'tractors.filters.types': 'Tractor Types',
    'tractors.filters.type.compact': 'Compact',
    'tractors.filters.type.row': 'Row Crop',
    'tractors.filters.type.speciality': 'Specialty',
    'tractors.filters.type.utility': 'Utility',
    'tractors.filters.type.orchard': 'Orchard',
    'tractors.filters.price': 'Price Range',
    'tractors.filters.hp': 'Horsepower',
    'tractors.filters.search': 'Search tractors...',
    'tractors.filters.location': 'Location',
    'tractors.filters.location.all': 'All Locations',
    'tractors.filters.availability': 'Availability',
    'tractors.filters.availability.all': 'All Status',
    'tractors.filters.availability.available': 'Available',
    'tractors.filters.availability.unavailable': 'Unavailable',
    'tractors.filters.rating': 'Minimum Rating',
    'tractors.filters.rating.any': 'Any Rating',
    'tractors.filters.action.cancel': 'Reset',
    'tractors.filters.action.apply': 'Apply Filters',
    'tractors.loading': 'Loading tractors...',
    'tractors.error': 'Failed to load tractors',
    'tractors.showing': 'Showing',
    'tractors.showing.unit': 'tractors',
    'tractors.showing.unit.single': 'tractor',
    'tractors.power': 'Power',
    'tractors.bookings': 'Bookings',
    'tractors.fuelLevel': 'Fuel Level',
    'tractors.fuelUnavailable': 'Fuel data unavailable',
    'tractors.location': 'Location not specified',
    'tractors.nextAvailable': 'Next Available',
    'tractors.pricePerHour': 'per hour',
    'tractors.bookNow': 'Book Now',
    'tractors.unavailable': 'Unavailable',
    'tractors.empty.title': 'No tractors found',
    'tractors.empty.subtitle': 'Try adjusting your filters',
    'tractors.dialog.title': 'Tractor Availability',
    'tractors.dialog.subtitle': 'Detailed status & next availability',
    'tractors.dialog.currentStatus': 'Current Status',
    'tractors.dialog.nextAvailable': 'Next Available',
    'tractors.dialog.currentLocation': 'Current Location',
    'tractors.dialog.messageUnavailable':
      'This tractor is unavailable right now. Please select another tractor or check back soon.',
    'tractors.dialog.close': 'Close',
    'tractors.dialog.notScheduled': 'Not scheduled',
    'tractors.dialog.locationNotSpecified': 'Not specified',
    'tractors.dialog.statusMessage': '{name} is currently {status}. Once the existing booking wraps up, it will be ready again for a new delivery.',
    'tractors.dialog.defaultMessage': 'This tractor is unavailable right now. Please select another tractor or check back soon.',
    'tractors.card.nextAvailableLabel': 'Next Available:',
    // Landing page new content
    'landing.hero.title': 'Power Your Farm',
    'landing.hero.titleSub': 'With Trusted Tractors',
    'landing.hero.description': 'Connect with reliable tractor owners across Nepal. Book, track, and manage your agricultural equipment needs with real-time location monitoring and secure payments.',
    'landing.hero.ctaBrowse': 'Browse Tractors',
    'landing.hero.ctaLearn': 'Learn More',
    'landing.hero.stats.districts': 'Districts',
    'landing.hero.stats.response': 'Response',
    'landing.hero.stats.support': 'Support',
    'landing.stats.title': 'Serving Farmers Across Nepal',
    'landing.stats.subtitle': 'Connecting agricultural communities with reliable tractor services',
    'landing.value.badge': 'Why Farmers Choose Us',
    'landing.value.title': 'Empowering Agriculture Across Nepal',
    'landing.value.subtitle': 'We bridge the gap between tractor owners and farmers, making agricultural equipment accessible to everyone.',
    'landing.value.coverage.title': 'Nationwide Coverage',
    'landing.value.coverage.desc': 'Access tractors across all 77 districts of Nepal, from Terai plains to Himalayan foothills.',
    'landing.value.tracking.title': 'Real-Time Tracking',
    'landing.value.tracking.desc': 'Monitor your booked tractor\'s location in real-time, ensuring transparency and security throughout the rental period.',
    'landing.value.secure.title': 'Secure & Reliable',
    'landing.value.secure.desc': 'Verified tractors, secure payment options (eSewa & COD), and comprehensive booking management for peace of mind.',
    'landing.value.trusted': 'Trusted by 1000+ Farmers',
    'landing.value.community': 'Join the growing community of agricultural professionals',
    'landing.cta.titleNew': 'Ready to Power Your Farm?',
    'landing.cta.description': 'Join thousands of farmers across Nepal who trust Tractor Sewa for their agricultural equipment needs. Book your tractor today and experience seamless service.',
    'landing.cta.browse': 'Browse Available Tractors',
    'landing.cta.createAccount': 'Create Account',
    'landing.cta.verified': 'Verified Tractors',
    'landing.cta.securePayments': 'Secure Payments',
    'landing.cta.realTimeTracking': 'Real-Time Tracking',
    'landing.hero.mainTitle': 'Tractor Booking System',
    'landing.hero.mainSubtitle': 'Rent, track, and manage tractors across Nepal with real-time visibility, secure payments, and powerful admin tools.',
    'landing.hero.browseButton': 'Browse Tractors',
    'landing.hero.howItWorksButton': 'How it works',
    'landing.stats.activeTractors': 'Active Tractors',
    'landing.stats.bookingsCompleted': 'Bookings Completed',
    'landing.stats.districtsCovered': 'Districts Covered',
    'landing.stats.avgRating': 'Avg. Rating',
    'landing.featured.title': 'Featured Tractors',
    'landing.featured.subtitle': 'High-demand models ready to book near you.',
    'landing.featured.seeAll': 'See all',
    'landing.featured.viewDetails': 'View details',
    'landing.featured.noTractors': 'No tractors available at the moment.',
    'landing.featured.checkBack': 'Check back soon for new listings!',
    'landing.howItWorks.title': 'How it works',
    'landing.howItWorks.subtitle': 'From search to payment in a few simple steps.',
    'landing.howItWorks.step1.title': 'Browse & Filter',
    'landing.howItWorks.step1.desc': 'Search by location, price, horsepower, and availability.',
    'landing.howItWorks.step2.title': 'Pick a Slot',
    'landing.howItWorks.step2.desc': 'Choose date and time that fits your schedule.',
    'landing.howItWorks.step3.title': 'Live Tracking',
    'landing.howItWorks.step3.desc': 'Follow your tractor in real-time on the map.',
    'landing.howItWorks.step4.title': 'Get to Work',
    'landing.howItWorks.step4.desc': 'Operator arrives and job starts on time.',
    'landing.howItWorks.step5.title': 'Easy Payment',
    'landing.howItWorks.step5.desc': 'Pay securely via eSewa or cash on delivery.',
    'landing.whyChoose.title': 'Why choose Tractor Sewa?',
    'landing.whyChoose.subtitle': 'Built for Nepal\'s terrain and agriculture needs.',
    'landing.whyChoose.feature1.title': 'Real-time Tracking',
    'landing.whyChoose.feature1.desc': 'Live GPS tracking and route visualization for every booking.',
    'landing.whyChoose.feature2.title': 'Flexible Payments',
    'landing.whyChoose.feature2.desc': 'Pay via eSewa or cash on delivery with instant verification.',
    'landing.whyChoose.feature3.title': 'Secure & Transparent',
    'landing.whyChoose.feature3.desc': 'Verified owners, clear pricing, and protected transactions.',
    'landing.whyChoose.feature4.title': 'Optimized Operations',
    'landing.whyChoose.feature4.desc': 'Smart logistics and utilization insights for admins.',
    'landing.cta.title': 'Need a tractor this week?',
    'landing.cta.subtitle': 'Check availability in your area and confirm instantly. Operators are vetted and ready to work on schedule.',
    'landing.cta.browseButton': 'Browse Tractors',
    'landing.cta.signInButton': 'Sign in',
    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'Manage your tractor rental business',
    'admin.dashboard.stats.tractors': 'Total Tractors',
    'admin.dashboard.stats.available': 'available',
    'admin.dashboard.stats.bookings': 'Total Bookings',
    'admin.dashboard.stats.paid': 'paid',
    'admin.dashboard.stats.revenue': 'Total Revenue',
    'admin.dashboard.stats.allTime': 'All time',
    'admin.dashboard.stats.users': 'Active Users',
    'admin.dashboard.stats.registered': 'Registered',
    'admin.dashboard.actions.title': 'Quick Actions',
    'admin.dashboard.actions.manageTractors': 'Manage Tractors',
    'admin.dashboard.actions.manageTractorsDesc': 'Add, edit, and remove tractors',
    'admin.dashboard.actions.manageBookings': 'Manage Bookings',
    'admin.dashboard.actions.manageBookingsDesc': 'Approve, reject or verify bookings',
    'admin.dashboard.actions.browseTractors': 'Browse Tractors',
    'admin.dashboard.actions.browseTractorsDesc': 'View your public tractor catalog',
    'admin.dashboard.actions.viewReports': 'View Reports',
    'admin.dashboard.actions.viewReportsDesc': 'Get insights and summaries',
    'admin.dashboard.recent.title': 'Recent Bookings',
    'admin.dashboard.recent.empty': 'No bookings yet',
    'admin.dashboard.recent.unknownTractor': 'Unknown Tractor',
    'admin.dashboard.recent.unknownUser': 'Unknown User',
    'admin.dashboard.loading': 'Loading...',
    'admin.dashboard.loadingData': 'Loading dashboard data...',
    // Login & Register
    'auth.welcome': 'Welcome Back',
    'auth.welcomeDesc': 'Sign in to your account to continue',
    'auth.getStarted': 'Get Started',
    'auth.getStartedDesc': 'Create your account to start renting tractors',
    'auth.login.title': 'Login',
    'auth.login.description': 'Use admin@tbs.local for admin access or any other email for customer access',
    'auth.register.title': 'Sign Up',
    'auth.register.description': 'Enter your details to create your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.passwordCreatePlaceholder': 'Create a password',
    'auth.passwordConfirmPlaceholder': 'Confirm your password',
    'auth.namePlaceholder': 'Your full name',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing in...',
    'auth.signUp': 'Sign up',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.creatingAccount': 'Creating account...',
    'auth.fillAllFields': 'Please fill in all fields',
    'auth.passwordsDontMatch': 'Passwords do not match',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    // About Page
    'about.hero.title': 'About Tractor Sewa',
    'about.hero.subtitle': 'Revolutionizing agriculture in Nepal through accessible technology, shared resources, and community-driven innovation.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc1': 'To democratize access to agricultural machinery by connecting tractor owners with farmers across Nepal, ensuring fair pricing, reliable service, and sustainable agricultural growth.',
    'about.mission.desc2': 'We believe every farmer deserves access to modern farming equipment, regardless of their location or economic status.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc1': 'To become Nepal\'s leading agricultural technology platform, empowering millions of farmers with accessible, efficient, and sustainable farming solutions.',
    'about.vision.desc2': 'We envision a future where technology bridges the gap between traditional farming and modern agricultural practices.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.trust.title': 'Trust & Security',
    'about.values.trust.desc': 'Verified owners, secure payments, and transparent transactions.',
    'about.values.community.title': 'Community First',
    'about.values.community.desc': 'Building a network that supports farmers and tractor owners.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Leveraging technology to modernize agriculture in Nepal.',
    'about.values.quality.title': 'Quality Service',
    'about.values.quality.desc': 'Verified fleet with professional operators and maintenance.',
    'about.impact.title': 'Our Impact',
    'about.impact.subtitle': 'Numbers that reflect our commitment to transforming agriculture',
    'about.impact.tractors': 'Active Tractors',
    'about.impact.tractors.desc': 'Verified & Ready',
    'about.impact.bookings': 'Bookings',
    'about.impact.bookings.desc': 'Successfully Completed',
    'about.impact.districts': 'Districts',
    'about.impact.districts.desc': 'Nationwide Coverage',
    'about.impact.rating': 'Rating',
    'about.impact.rating.desc': 'Average User Rating',
    'about.journey.title': 'Our Journey',
    'about.journey.subtitle': 'Milestones that shaped our growth',
    'about.journey.2020': 'Founded',
    'about.journey.2020.desc': 'Started with a vision to digitize tractor rentals',
    'about.journey.2021': '100 Tractors',
    'about.journey.2021.desc': 'Reached our first major milestone',
    'about.journey.2022': '5,000 Bookings',
    'about.journey.2022.desc': 'Served thousands of farmers across Nepal',
    'about.journey.2023': 'Nationwide',
    'about.journey.2023.desc': 'Expanded to all 77 districts of Nepal',
    'about.journey.2024': '10,000+ Users',
    'about.journey.2024.desc': 'Growing community of farmers and owners',
    'about.why.title': 'Why Choose Tractor Sewa?',
    'about.why.subtitle': 'What sets us apart in the agricultural technology space',
    'about.why.network.title': 'Nationwide Network',
    'about.why.network.desc': 'Access to tractors across all 77 districts of Nepal. Find the right equipment near you, no matter where you are.',
    'about.why.tracking.title': 'Real-Time Tracking',
    'about.why.tracking.desc': 'Monitor your tractor\'s location and route in real-time. Know exactly when your equipment will arrive.',
    'about.why.verified.title': 'Verified & Trusted',
    'about.why.verified.desc': 'All tractors and operators are verified. We ensure quality, reliability, and professional service standards.',
    'about.cta.title': 'Join Our Growing Community',
    'about.cta.desc': 'Whether you\'re a farmer looking for equipment or a tractor owner wanting to earn, Tractor Sewa is here to connect you.',
    'about.cta.browse': 'Browse Tractors',
    'about.cta.contact': 'Contact Us',
    // Contact Page
    'contact.hero.title': 'Get in Touch',
    'contact.hero.subtitle': 'Have questions? We\'re here to help. Reach out to us and we\'ll respond as soon as possible.',
    'contact.getInTouch': 'Get in Touch',
    'contact.getInTouch.desc': 'Have questions about booking a tractor or listing your vehicle? Our team is ready to assist you.',
    'contact.phone': 'Phone',
    'contact.phone.number': '+977 9800000000',
    'contact.phone.hours': 'Mon-Fri: 8am - 5pm',
    'contact.email': 'Email',
    'contact.email.address': 'info@tractorsewa.com',
    'contact.email.support': '24/7 Support',
    'contact.address': 'Address',
    'contact.address.location': 'Kathmandu, Nepal',
    'contact.address.visit': 'Visit our office',
    'contact.form.title': 'Send us a Message',
    'contact.form.subtitle': 'Fill out the form below and we\'ll get back to you within 24 hours.',
    'contact.form.firstName': 'First Name *',
    'contact.form.lastName': 'Last Name *',
    'contact.form.email': 'Email *',
    'contact.form.phone': 'Phone',
    'contact.form.subject': 'Subject *',
    'contact.form.subject.placeholder': 'What is this regarding?',
    'contact.form.message': 'Message *',
    'contact.form.message.placeholder': 'Tell us how we can help you...',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you soon.',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekday': 'Monday - Friday',
    'contact.hours.weekday.time': '8:00 AM - 5:00 PM',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.saturday.time': '9:00 AM - 2:00 PM',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.sunday.time': 'Closed',
    'contact.hours.email24': 'Email support available 24/7',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'How do I book a tractor?',
    'contact.faq.a1': 'Simply browse our available tractors, select your preferred dates and time, and complete the booking. You can pay via eSewa or cash on delivery.',
    'contact.faq.q2': 'What areas do you cover?',
    'contact.faq.a2': 'We operate across all 77 districts of Nepal. Use our location filter to find tractors near you.',
    'contact.faq.q3': 'How do I list my tractor?',
    'contact.faq.a3': 'Contact us through this form or email us at info@tractorsewa.com. Our team will guide you through the registration process.',
    'contact.faq.q4': 'What payment methods are accepted?',
    'contact.faq.a4': 'We accept eSewa for online payments and cash on delivery for your convenience.',
    'contact.help.title': 'We\'re Here to Help',
    'contact.help.desc': 'Our support team is committed to providing you with the best possible service. Whether you have questions about bookings, need technical assistance, or want to partner with us, we\'re just a message away.',
    'contact.help.response': 'Average Response Time:',
    'contact.help.response.time': 'Under 2 hours',
    'contact.help.languages': 'Support Languages:',
    'contact.help.languages.list': 'English & Nepali',
    // Privacy Page
    'privacy.hero.title': 'Privacy Policy',
    'privacy.hero.subtitle': 'Your privacy is important to us. This policy explains how we collect, use, and protect your personal information.',
    'privacy.hero.lastUpdated': 'Last Updated:',
    'privacy.hero.effectiveDate': 'Effective Date:',
    'privacy.hero.december2024': 'December 2024',
    'privacy.hero.january2024': 'January 1, 2024',
    'privacy.summary.title': 'Quick Summary',
    'privacy.summary.p1': 'We collect only necessary information to provide our services',
    'privacy.summary.p2': 'Your data is encrypted and stored securely',
    'privacy.summary.p3': 'We never sell your personal information to third parties',
    'privacy.summary.p4': 'You have full control over your data and can request deletion at any time',
    'privacy.section.collection.title': 'Information Collection',
    'privacy.section.collection.p1': 'We collect information you provide directly to us when you:',
    'privacy.section.collection.p2': '• Create an account or profile on our platform',
    'privacy.section.collection.p3': '• Book a tractor or list your equipment',
    'privacy.section.collection.p4': '• Contact us for customer support',
    'privacy.section.collection.p5': '• Subscribe to our newsletter or marketing communications',
    'privacy.section.collection.p6': '• Participate in surveys or promotional activities',
    'privacy.section.collection.p7': '',
    'privacy.section.collection.p8': 'This information may include:',
    'privacy.section.collection.p9': '• Personal identification (name, email, phone number)',
    'privacy.section.collection.p10': '• Location data for service delivery',
    'privacy.section.collection.p11': '• Payment information (processed securely through third-party providers)',
    'privacy.section.collection.p12': '• Profile pictures and account preferences',
    'privacy.section.collection.p13': '• Communication history and support tickets',
    'privacy.section.use.title': 'Use of Information',
    'privacy.section.use.p1': 'We use the collected information to:',
    'privacy.section.use.p2': '• Provide, maintain, and improve our services',
    'privacy.section.use.p3': '• Process transactions and manage bookings',
    'privacy.section.use.p4': '• Send booking confirmations, updates, and notifications',
    'privacy.section.use.p5': '• Verify user identity and prevent fraud',
    'privacy.section.use.p6': '• Respond to customer service requests',
    'privacy.section.use.p7': '• Analyze usage patterns to enhance user experience',
    'privacy.section.use.p8': '• Send marketing communications (with your consent)',
    'privacy.section.use.p9': '• Comply with legal obligations and enforce our terms',
    'privacy.section.use.p10': '',
    'privacy.section.use.p11': 'We do not sell your personal information to third parties.',
    'privacy.section.security.title': 'Data Security',
    'privacy.section.security.p1': 'We implement comprehensive security measures to protect your data:',
    'privacy.section.security.p2': '• Industry-standard encryption (SSL/TLS) for data transmission',
    'privacy.section.security.p3': '• Secure password hashing and authentication protocols',
    'privacy.section.security.p4': '• Regular security audits and vulnerability assessments',
    'privacy.section.security.p5': '• Access controls and employee training on data protection',
    'privacy.section.security.p6': '• Secure payment processing through certified providers',
    'privacy.section.security.p7': '',
    'privacy.section.security.p8': 'While we strive to protect your information, no method of transmission over the internet is 100% secure. We cannot guarantee absolute security but are committed to maintaining the highest standards.',
    'privacy.section.storage.title': 'Data Storage & Retention',
    'privacy.section.storage.p1': 'Data Storage:',
    'privacy.section.storage.p2': '• Your data is stored on secure servers with appropriate safeguards',
    'privacy.section.storage.p3': '• We use reputable cloud service providers that comply with international security standards',
    'privacy.section.storage.p4': '',
    'privacy.section.storage.p5': 'Data Retention:',
    'privacy.section.storage.p6': '• Account information: Retained while your account is active',
    'privacy.section.storage.p7': '• Booking records: Retained for 7 years for legal and accounting purposes',
    'privacy.section.storage.p8': '• Marketing data: Retained until you unsubscribe',
    'privacy.section.storage.p9': '• Support communications: Retained for 3 years',
    'privacy.section.storage.p10': '',
    'privacy.section.storage.p11': 'You can request deletion of your data at any time, subject to legal requirements.',
    'privacy.section.rights.title': 'Your Rights',
    'privacy.section.rights.p1': 'You have the right to:',
    'privacy.section.rights.p2': '• Access your personal data',
    'privacy.section.rights.p3': '• Correct inaccurate or incomplete information',
    'privacy.section.rights.p4': '• Request deletion of your data (right to be forgotten)',
    'privacy.section.rights.p5': '• Object to processing of your data',
    'privacy.section.rights.p6': '• Request data portability',
    'privacy.section.rights.p7': '• Withdraw consent for marketing communications',
    'privacy.section.rights.p8': '• File a complaint with relevant data protection authorities',
    'privacy.section.rights.p9': '',
    'privacy.section.rights.p10': 'To exercise these rights, contact us at privacy@tractorsewa.com',
    'privacy.section.thirdparty.title': 'Third-Party Services',
    'privacy.section.thirdparty.p1': 'We may use third-party services that have access to your information:',
    'privacy.section.thirdparty.p2': '• Payment processors (eSewa, etc.) for transaction processing',
    'privacy.section.thirdparty.p3': '• Cloud hosting providers for data storage',
    'privacy.section.thirdparty.p4': '• Analytics services to understand platform usage',
    'privacy.section.thirdparty.p5': '• Email service providers for communications',
    'privacy.section.thirdparty.p6': '• Map services for location features',
    'privacy.section.thirdparty.p7': '',
    'privacy.section.thirdparty.p8': 'These services are bound by their own privacy policies and security standards. We only share information necessary for them to perform their services.',
    'privacy.section.cookies.title': 'Cookies & Tracking',
    'privacy.section.cookies.p1': 'We use cookies and similar technologies to:',
    'privacy.section.cookies.p2': '• Maintain your session and login status',
    'privacy.section.cookies.p3': '• Remember your preferences and settings',
    'privacy.section.cookies.p4': '• Analyze website traffic and usage patterns',
    'privacy.section.cookies.p5': '• Provide personalized content and advertisements',
    'privacy.section.cookies.p6': '',
    'privacy.section.cookies.p7': 'You can control cookies through your browser settings. However, disabling cookies may affect platform functionality.',
    'privacy.section.children.title': 'Children\'s Privacy',
    'privacy.section.children.p1': 'Our services are not intended for individuals under 18 years of age. We do not knowingly collect personal information from children.',
    'privacy.section.children.p2': '',
    'privacy.section.children.p3': 'If you believe we have collected information from a child, please contact us immediately, and we will take steps to delete such information.',
    'privacy.changes.title': 'Changes to This Policy',
    'privacy.changes.p1': 'We may update this Privacy Policy from time to time to reflect changes in our practices or for legal, operational, or regulatory reasons. We will notify you of any material changes by:',
    'privacy.changes.p2': '• Posting the updated policy on this page with a new "Last Updated" date',
    'privacy.changes.p3': '• Sending an email notification to registered users',
    'privacy.changes.p4': '• Displaying a prominent notice on our platform',
    'privacy.changes.p5': '',
    'privacy.changes.p6': 'Your continued use of our services after changes become effective constitutes acceptance of the updated policy.',
    'privacy.contact.title': 'Questions About Privacy?',
    'privacy.contact.desc': 'If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please don\'t hesitate to contact us.',
    'privacy.contact.email1': 'privacy@tractorsewa.com',
    'privacy.contact.email2': 'info@tractorsewa.com',
    'privacy.contact.button': 'Contact Us',
    // User Dashboard
    'dashboard.title': 'My Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.stats.totalBookings': 'Total Bookings',
    'dashboard.stats.activeBookings': 'Active Bookings',
    'dashboard.stats.totalSpent': 'Total Spent',
    'dashboard.myBookings': 'My Bookings',
    'dashboard.empty.title': 'No bookings yet',
    'dashboard.empty.subtitle': 'Start by browsing available tractors',
    'dashboard.loading': 'Loading...',
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account information',
    'profile.information': 'Profile Information',
    'profile.fullName': 'Full Name',
    'profile.emailAddress': 'Email Address',
    'profile.emailCannotChange': 'Email cannot be changed',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.cancel': 'Cancel',
    'profile.uploading': 'Uploading...',
    'profile.enterName': 'Enter your name',
    // Tracking
    'tracking.title': 'Real-Time Tractor Tracking',
    'tracking.subtitle': 'View the live route, ETA, and delivery progress for your approved bookings.',
    'tracking.selectBooking': 'Select booking',
    'tracking.noBookings': 'You don\'t have any bookings ready for tracking yet. Once a tractor is approved, its route will appear here.',
    'tracking.loading': 'Loading...',
    // Payment
    'payment.success.title': 'Payment Successful!',
    'payment.success.verifying': 'Verifying payment...',
    'payment.success.confirmed': 'Your booking has been confirmed. You will be redirected to your dashboard shortly.',
    'payment.success.goDashboard': 'Go to Dashboard',
    'payment.failure.title': 'Payment Failed',
    'payment.failure.withBooking': 'Your booking was created but payment could not be processed. Please try again or use Cash on Delivery.',
    'payment.failure.withoutBooking': 'Your payment could not be processed. Please try again.',
    'payment.failure.goDashboard': 'Go to Dashboard',
    'payment.invalidBookingId': 'Invalid booking ID',
    'payment.verified': 'Payment verified successfully!',
    'payment.verificationFailed': 'Payment verification failed',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.returnHome': 'Return to Home',
    // MapPreview
    'mappreview.title': 'Leaflet Map Preview',
    'mappreview.description': 'Use this page to confirm Leaflet tiles load correctly in your environment.',
    // Common
    'common.loading': 'Loading...',
    'common.welcomeBack': 'Welcome back',
    'dashboard.status.confirmed': 'Confirmed',
    'dashboard.status.pending': 'Pending',
    'dashboard.status.completed': 'Completed',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.status.refund_requested': 'Refund Requested',
    'dashboard.payment.paid': 'Paid',
    'dashboard.payment.pending': 'Payment Pending',
    'dashboard.payment.failed': 'Payment Failed',
    'dashboard.cancellation.success': 'Cancellation request submitted',
    'dashboard.cancellation.failed': 'Failed to cancel booking',
    'dashboard.totalAmount': 'Total amount',
    'dashboard.cancelBooking': 'Cancel Booking',
    'dashboard.trackTractor': 'Track Tractor',
    'dashboard.cancelDialog.title': 'Cancel Booking',
    'dashboard.cancelDialog.description.paid': 'Are you sure you want to request a refund for this booking? A 3% fee will be deducted from your refund. This request will be reviewed by an admin.',
    'dashboard.cancelDialog.description.unpaid': 'Are you sure you want to cancel this booking? This action cannot be undone.',
    'dashboard.cancelDialog.cancel': 'Cancel',
    'dashboard.cancelDialog.confirm': 'Confirm',
  },
  ne: {
    'brand.taglinePrimary': 'रियल-टाइम ट्र्याकिङ सहितको भरपर्दो ट्र्याक्टर भाडा सेवा',
    'brand.taglineSecondary': 'स्थान ट्र्याकिङसहित सुरक्षित बुकिङ अब सहज',
    'brand.subtitle': 'सुरक्षित भाडा प्लेटफर्म',
    'nav.home': 'गृहपृष्ठ',
    'nav.platform': 'प्लेटफर्म',
    'nav.fleet': 'फ्लीट',
    'nav.tractors': 'ट्र्याक्टरहरू',
    'nav.about': 'हाम्रो बारेमा',
    'nav.contact': 'सम्पर्क',
    'nav.privacy': 'गोपनीयता नीति',
    'nav.insights': 'अन्तर्दृष्टि',
    'nav.myBookings': 'मेरो बुकिङ',
    'nav.bookTractor': 'ट्र्याक्टर बुक',
    'nav.book': 'बुक',
    'nav.createAccount': 'खाता बनाउनुहोस्',
    'nav.login': 'लगइन',
    'nav.navigation': 'नेभिगेसन',
    'nav.profileSettings': 'प्रोफाइल सेटिङ',
    'nav.logout': 'लगआउट',
    'nav.customer': 'ग्राहक',
    'nav.administrator': 'प्रशासक',
    'nav.languageToggle': 'English',
    'nav.adminPanel': 'एडमिन प्यानल',
    'nav.more': 'थप',
    'nav.language': 'भाषा',
    'landing.hero.badge': 'विश्वसनीय ट्र्याक्टर भाडा प्लेटफर्म',
    'landing.hero.heading': 'रियल-टाइम लोकेशन ट्र्याकिङसहित गुणस्तरीय ट्र्याक्टर भाडामा लिऔँ।',
    'landing.hero.subtitle':
      'हाम्रो प्लेटफर्मबाट निश्चिन्त भएर ट्र्याक्टर बुक गर्नुहोस्। सुरक्षित बुकिङ, रियल-टाइम लोकेशन ट्र्याकिङ, र नेपालका सबै भू-भागमा भरपर्दो सेवा।',
    'landing.hero.ctaPrimary': 'ट्र्याक्टर शेड्युल गर्नुहोस्',
    'landing.hero.ctaSecondary': 'प्लेटफर्म हेर्नुहोस्',
    'landing.stats.districts.label': 'कभर भएका जिल्ला',
    'landing.stats.districts.desc': 'तराईदेखि हिमाली भेगसम्म',
    'landing.stats.response.label': 'औसत प्रतिक्रिया समय',
    'landing.stats.response.desc': 'छिटो ट्र्याक्टर अभिरचना',
    'landing.stats.utilization.label': 'फ्लीट उपयोग',
    'landing.stats.utilization.desc': 'उत्पादक फ्लीट व्यवस्थापन',
    'landing.dispatch.badge': 'फ्लीट स्न्यापशट',
    'landing.dispatch.title': 'लाईभ डिस्प्याच बोर्ड',
    'landing.dispatch.liveTag': 'लाईभ ट्र्याकिङ',
    'landing.dispatch.loading': 'डिस्प्याच डेटा लोड भइरहेकाे छ...',
    'landing.dispatch.activity.title': 'आजको गतिविधि',
    'landing.dispatch.activity.body': 'चितवन क्षेत्रमा उच्च माग',
    'landing.dispatch.activity.caption': 'आज धेरै बुकिङ छन्। मनपर्ने समय सुरक्षित गर्न अग्रिम बुक गर्नुहोस्।',
    'landing.dispatch.etaLabel': 'अनुमानित समय',
    'landing.dispatch.soil.title': 'माटो संरक्षण अलर्ट',
    'landing.dispatch.soil.badge': 'मध्यम',
    'landing.dispatch.soil.body': 'ललितपुर र Sunsari मा दोहोरो पास लिमिटर प्रयोग गरेर माथिल्लो माटो जोगाउनुहोस्।',
    'landing.dispatch.fallback.name': 'लमजुङ भ्याली रन',
    'landing.dispatch.fallback.location': 'लमजुङ भ्याली',
    'landing.dispatch.fallback.distance': '४२ किमी',
    'landing.dispatch.fallback.terrain': 'मिश्रित भू-भाग',
    'landing.dispatch.fallback.eta': '१८ मिनेट',
    'landing.dispatch.fallback.efficiency': 'दक्षता १२% माथि',
    'landing.dispatch.status.on_route': 'मार्गमा',
    'landing.dispatch.status.available': 'उपलब्ध',
    'landing.dispatch.status.in_use': 'प्रयोगमा',
    'landing.platform.badge': 'प्लेटफर्म क्षमताहरू',
    'landing.platform.title': 'कृषि-लोजिस्टिक्सका लागि निर्माण गरिएको नियन्त्रण केन्द्र।',
    'landing.platform.subtitle':
      'Tractor Sewa ले सहकारी, अपरेटर र फार्म होल्डिङका लागि पूर्ण फ्लीट व्यवस्थापन प्रदान गर्दछ। रियल-टाइम ट्र्याकिङ, बुकिङ रेकर्ड र मर्मत सबै एक ठाउँमा।',
    'landing.platform.cta': 'गाइडेड अनबोर्डिङ माग्नुहोस्',
    'landing.platform.features.tracking.title': 'रियल-टाइम ट्र्याकिङ',
    'landing.platform.features.tracking.desc':
      'सुरक्षाका लागि ट्र्याक्टरको स्थान निरन्तर हेर्नुहोस्। उपकरण कुन ठाउँमा छ, सधैं थाहा हुन्छ।',
    'landing.platform.features.tracking.meta': 'GPS ट्र्याकिङ • लोकेशन अपडेट • सुरक्षा निगरानी',
    'landing.platform.features.operations.title': 'एकीकृत अपरेसन',
    'landing.platform.features.operations.desc':
      'एसेट ट्र्याकिङ, बुकिङ, भुक्तानी र मर्मतका सबै वर्कफ्लो एकै कनसोलमा— फ्लीट व्यवस्थापनलाई सहज बनाउँदै।',
    'landing.platform.features.operations.meta': 'डिजिटल रेकर्ड • स्वचालित वर्कफ्लो • विश्लेषण-तयार डेटा',
    'landing.platform.features.logistics.title': 'स्मार्ट लोजिस्टिक्स',
    'landing.platform.features.logistics.desc':
      'इन्धन लागत र डाउनटाइम घटाउन दक्ष डिस्प्याच र रुटिङ। नेपालको विविध भू-भागका लागि अनुकूल।',
    'landing.platform.features.logistics.meta': 'रुट अनुकूलन • इन्धन दक्षता • समय व्यवस्थापन',
    'landing.platform.cards.track.title': 'लाईभ ट्र्याकिङ',
    'landing.platform.cards.track.body':
      'सक्रिय बुकिङको क्रममा नक्शामा आफ्नाे उपकरण पछ्याउन Live Tracking मा जाऔँ।',
    'landing.platform.cards.track.linkLabel': 'Live Tracking',
    'landing.platform.cards.catalog.title': 'स्मार्ट क्याटलग',
    'landing.platform.cards.catalog.body':
      'रियल फोटो, इन्धन स्थिति र उपलब्धतासहित ट्र्याक्टर सूची Tractors पेजमा हेर्नुहोस्।',
    'landing.platform.cards.catalog.linkLabel': 'Tractors',
    'landing.platform.cards.admin.title': 'एडमिन कन्सोल',
    'landing.platform.cards.admin.body':
      'ट्र्याक्टर थप/सम्पादन, रिफन्ड स्वीकृति र अडिट कार्य Admin Dashboard बाट व्यवस्थापन गर्नुहोस्।',
    'landing.platform.cards.admin.linkLabel': 'Admin Dashboard',
    'landing.workflow.badge': 'अपरेशनल वर्कफ्लो',
    'landing.workflow.title': 'तीन सरल चरणमा बुकिङ प्रक्रिया।',
    'landing.workflow.subtitle':
      'Tractor Sewa ले ट्र्याक्टर खोज्न, बुक गर्न र ट्र्याकिङ गर्न सजिलो बनाउँछ। समयमै उपकरण पाउनुहोस्।',
    'landing.workflow.step1.title': 'उपलब्ध ट्र्याक्टर हेर्नुहोस्',
    'landing.workflow.step1.desc':
      'स्थान, पावर र उपलब्धताको आधारमा फिल्टर गरेर आफ्नो फ्लीट छान्नुहोस्।',
    'landing.workflow.step2.title': 'बुक र पुष्टि गर्नुहोस्',
    'landing.workflow.step2.desc':
      'मिति/समय छानेपछि eSewa वा COD जस्ता सुरक्षित विकल्पबाट पुष्टि गर्नुहोस्।',
    'landing.workflow.step3.title': 'ट्र्याक र निगरानी',
    'landing.workflow.step3.desc': 'बुक गरिएको ट्र्याक्टरको मार्ग र स्थिति रियल-टाइम ट्र्याकिङमा हेर्नुहोस्।',
    'landing.insights.badge': 'गतिमा अन्तर्दृष्टि',
    'landing.insights.title': 'तुरुन्त प्रयोग गर्न मिल्ने अपरेशनल बुद्धिमत्ता।',
    'landing.insights.subtitle':
      'वास्तविक प्रयोग, इन्धन दक्षता र बुकिङ ट्रेन्डले रुट योजना र क्षमताको पूर्वतयारीमा मद्दत गर्छ।',
    'landing.insights.highlight.satisfaction.label': 'ग्राहक सन्तुष्टि',
    'landing.insights.highlight.satisfaction.caption': '१,२००+ बुकिङको आधारमा',
    'landing.insights.highlight.ontime.label': 'समयमै डेलिभरी',
    'landing.insights.highlight.ontime.caption': 'सबै जिल्लामा भरपर्दो सेवा',
    'landing.insights.highlight.availability.label': 'फ्लीट उपलब्धता',
    'landing.insights.highlight.availability.caption': 'उच्च अपटाइम र तत्पर अवस्था',
    'landing.insights.dashboard.title': 'फ्लीट उपयोग ड्यासबोर्ड',
    'landing.insights.dashboard.card.title': 'मौसमी पूर्वानुमान — फागुन झ्याल',
    'landing.insights.dashboard.card.body':
      'प्रदेश २ मा वर्षात्को कारण माग बढ्ने अपेक्षा। दोश्रो जोत्नुअघि जनकपुर र वीरगञ्जमा स्ट्यान्डबाइ ट्र्याक्टर सक्रिय गर्नुहोस्।',
    'landing.insights.testimonial1':
      '"बुकिङ प्रणाली अत्यन्त सरल र छिटो छ। केही मिनेटमै चाहिएको ट्र्याक्टर पाउछौँ, र ट्र्याकिङले थप विश्वास दिलाउँछ।"',
    'landing.insights.testimonial2':
      '"एकीकृत ड्यासबोर्डले कागजी झन्झट ५०%ले घटायो र ९७% समयमै डेलिभरी सम्भव बनायो। रियल-टाइम ट्र्याकिङले सञ्चालन व्यवस्थित हुन्छ।"',
    'landing.testimonial1.role': 'कास्की, सहकारी प्रमुख',
    'landing.testimonial2.role': 'हिमालयन एग्रो, सञ्चालन प्रमुख',
    'landing.insights.dataFreshness.title': 'डेटा ताजा स्थिति',
    'landing.insights.dataFreshness.body': 'कामका क्रममा ५–१५ सेकेन्डको अन्तरमा स्थिति अपडेट।',
    'landing.insights.privacy.title': 'गोपनीयता र नियन्त्रण',
    'landing.insights.privacy.body': 'डाटा ट्रान्जिटमा इन्क्रिप्टेड, सञ्चयन अवधि एडमिनले तय गर्छ।',
    'landing.insights.exports.title': 'एक्सपोर्ट',
    'landing.insights.exports.body': 'बुकिङ, ट्र्याक्टर र एनालिटिक्सका लागि एक-क्लिक CSV एक्सपोर्ट।',
    'landing.pricing.badge': 'पारदर्शी मूल्य',
    'landing.pricing.title': 'आप्नो उत्पादन क्षेत्रसँग मिल्ने लचिलो योजना।',
    'landing.pricing.subtitle':
      'सरल र स्पष्ट मूल्य, प्रत्येक बुकिङमा अपरेटर प्रमाणीकरण, मर्मत आश्वासन र डिजिटल अभिलेख समावेश।',
    'landing.pricing.plan.standard.title': 'मानक सेवा',
    'landing.pricing.plan.standard.desc': 'छोटो समुदाय वा किसान समूहका लागि छिटो र भरपर्दो सेवा।',
    'landing.pricing.plan.standard.badge': 'मूल योजना',
    'landing.pricing.plan.standard.feature1': '• ३० मिनेटभित्र अपरेटर पठाउने लक्ष्य',
    'landing.pricing.plan.standard.feature2': '• eSewa वा नगद भुक्तानीका विकल्प',
    'landing.pricing.plan.standard.feature3': '• रूटीन मर्मत र इन्धन आश्वासन',
    'landing.pricing.plan.standard.cta': 'मानक योजना बुक गर्नुहोस्',
    'landing.pricing.plan.premium.title': 'प्रिमियम सेवा',
    'landing.pricing.plan.premium.desc': 'सहकारी तथा पुनरावर्ती ग्राहकका लागि थप समन्वय।',
    'landing.pricing.plan.premium.badge': 'पूर्ण सहयोग',
    'landing.pricing.plan.premium.feature1': '• प्राथमिकता डिस्प्याच र समर्पित समन्वयकर्ता',
    'landing.pricing.plan.premium.feature2': '• रियल-टाइम ट्र्याकिङ र इन्धन रिपोर्ट',
    'landing.pricing.plan.premium.feature3': '• लचिलो बिलिङ र डिजिटल कागजात',
    'landing.pricing.plan.premium.cta': 'प्रिमियम योजना बुक गर्नुहोस्',
    'landing.fleet.badge': 'विशेष ट्र्याक्टरहरू',
    'landing.fleet.title': 'अहिले उपलब्ध प्रमुख ट्र्याक्टरहरू।',
    'landing.fleet.subtitle':
      'प्रत्येक मेसिन स्थान-ट्र्याक, अपरेटर प्रमाणीकरण र तपाईंको आवश्यकता अनुसार तयार।',
    'landing.fleet.cta': 'सबै ट्र्याक्टरहरू हेर्नुहोस्',
    'landing.sustainable.badge': 'टिकाउ नतिजा',
    'landing.sustainable.deskLabel': 'दिगोपन डेस्क',
    'landing.sustainable.title': 'शान्तिका लागि रियल-टाइम लोकेशनसहित सुरक्षित बुकिङ।',
    'landing.sustainable.body':
      'हाम्रो प्लेटफर्मले सुरक्षा र सञ्चालन निगरानीका लागि रियल-टाइम ट्र्याकिङ प्रदान गर्छ। Tractor Sewa बाट भाडाको अवधिभर ट्र्याक्टरको लोकेशन हेर्नुस्।',
    'landing.sustainable.stat1.title': 'माथिल्लो माटो जोगियो',
    'landing.sustainable.stat1.body': '२०२४ मा १२,८०० हे. कृषि भूमि सुरक्षित',
    'landing.sustainable.stat2.title': 'अपरेटर अनुपालन',
    'landing.sustainable.stat2.body': 'सुरक्षा तथा चेकलिस्टमा ९८.६% पालना',
    'landing.sustainable.quote':
      '"Tractor Sewa को लोकेशन ट्र्याकिङले हामीलाई सञ्चालनमा भरपर्दो बनायो। वास्तविक-समय अनुगमनले सुरक्षा र स्रोत व्यवस्थापनमा आत्मविश्वास दिन्छ।"',
    'landing.sustainable.quote.author': 'नवीन बिष्ट',
    'landing.sustainable.quote.role': 'एग्रोनोमी निर्देशक, नेपाल एग्रोल्याब',
    'landing.cta.badge': 'सुरक्षित र भरपर्दो',
    'landing.cta.title': 'के तपाईं अर्को ट्र्याक्टर भाडा लिन तयार हुनुहुन्छ?',
    'landing.cta.subtitle':
      'Tractor Sewa प्रयोग गर्ने किसान र सहकारीसँगै जडान हुनुहोस्, रियल-टाइम ट्र्याकिङसहित गुणवत्तापूर्ण सेवा पाउनुहोस्।',
    'landing.cta.primary': 'आजै सुरु गर्नुहोस्',
    'landing.cta.secondary': 'कन्सोलमा लगइन गर्नुहोस्',
    'landing.footer.tagline': 'नेपालका लागि भरपर्दो ट्र्याक्टर भाडा प्लेटफर्म',
    'landing.footer.copy': '© २०२५ Tractor Sewa। नेपालभर सुरक्षित ट्र्याक्टर भाडा सेवा।',
    'landing.dispatch.fallback.destination': 'गन्तव्य तोकिएको छैन',
    'landing.dispatch.dynamicTerrain': 'मिश्रित भूभाग',
    'landing.dispatch.etaFallback': '—',
    'landing.dispatch.fallback.efficiency': 'दक्षता १२% माथि',
    'status.available': 'उपलब्ध',
    'status.unavailable': 'अनुपलब्ध',
    'status.booked': 'बुक भएको',
    'status.in_use': 'प्रयोगमा',
    'tractors.header.title': 'उपलब्ध ट्र्याक्टरहरू हेर्नुहोस्',
    'tractors.header.subtitle': 'आफ्नो क्षेत्रमा उपलब्ध र प्रयोगमा रहेका ट्र्याक्टर खोज्नुहोस्',
    'tractors.filters.toggle.hide': 'फिल्टर लुकाउनुहोस्',
    'tractors.filters.toggle.show': 'उन्नत फिल्टर',
    'tractors.filters.types': 'ट्र्याक्टर प्रकार',
    'tractors.filters.type.compact': 'कम्प्याक्ट',
    'tractors.filters.type.row': 'रो क्रप',
    'tractors.filters.type.speciality': 'विशेष',
    'tractors.filters.type.utility': 'युटिलिटी',
    'tractors.filters.type.orchard': 'अर्चर्ड',
    'tractors.filters.price': 'मूल्य दायरा',
    'tractors.filters.hp': 'हर्सपावर',
    'tractors.filters.search': 'ट्र्याक्टर खोज्नुहोस्...',
    'tractors.filters.location': 'स्थान',
    'tractors.filters.location.all': 'सबै स्थान',
    'tractors.filters.availability': 'उपलब्धता',
    'tractors.filters.availability.all': 'सबै स्थिति',
    'tractors.filters.availability.available': 'उपलब्ध',
    'tractors.filters.availability.unavailable': 'अनुपलब्ध',
    'tractors.filters.rating': 'न्यूनतम रेटिङ',
    'tractors.filters.rating.any': 'कुनै पनि रेटिङ',
    'tractors.filters.action.cancel': 'रिसेट',
    'tractors.filters.action.apply': 'फिल्टर लागू गर्नुहोस्',
    'tractors.loading': 'ट्र्याक्टरहरू लोड भइरहेको छ...',
    'tractors.error': 'ट्र्याक्टर लोड गर्न असफल',
    'tractors.showing': 'कुल',
    'tractors.showing.unit': 'ट्र्याक्टर',
    'tractors.showing.unit.single': 'ट्र्याक्टर',
    'tractors.power': 'पावर',
    'tractors.bookings': 'बुकिङ',
    'tractors.fuelLevel': 'इन्धन स्तर',
    'tractors.fuelUnavailable': 'इन्धन जानकारी उपलब्ध छैन',
    'tractors.location': 'स्थान निर्दिष्ट गरिएको छैन',
    'tractors.nextAvailable': 'अर्को उपलब्ध समय',
    'tractors.pricePerHour': 'प्रति घण्टा',
    'tractors.bookNow': 'बुक गर्नुहोस्',
    'tractors.unavailable': 'अनुपलब्ध',
    'tractors.empty.title': 'ट्र्याक्टर फेला परेन',
    'tractors.empty.subtitle': 'कृपया फिल्टर परिवर्तन गरेर पुन: प्रयास गर्नुहोस्',
    'tractors.dialog.title': 'ट्र्याक्टर उपलब्धता',
    'tractors.dialog.subtitle': 'विस्तृत स्थिति र आगामी उपलब्धता',
    'tractors.dialog.currentStatus': 'वर्तमान स्थिति',
    'tractors.dialog.nextAvailable': 'अर्को उपलब्ध समय',
    'tractors.dialog.currentLocation': 'हालको स्थान',
    'tractors.dialog.messageUnavailable':
      'यो ट्र्याक्टर अहिले उपलब्ध छैन। कृपया अर्को ट्र्याक्टर छान्नुहोस् वा पछि पुन: प्रयास गर्नुहोस्।',
    'tractors.dialog.close': 'बन्द गर्नुहोस्',
    'tractors.dialog.notScheduled': 'निर्धारण गरिएको छैन',
    'tractors.dialog.locationNotSpecified': 'निश्चित गरिएको छैन',
    'tractors.dialog.statusMessage': '{name} अहिले {status} अवस्थामा छ। यो बुकिङ पूरा भएपछि तुरुन्त अर्को वितरणका लागि तयार हुनेछ।',
    'tractors.dialog.defaultMessage': 'यो ट्र्याक्टर हाल उपलब्ध छैन। कृपया अर्को ट्र्याक्टर छान्नुहोस् वा पछि फेरि प्रयास गर्नुहोस्।',
    'tractors.card.nextAvailableLabel': 'अर्को उपलब्ध:',
    // Landing page new content
    'landing.hero.title': 'आफ्नो खेतलाई शक्ति दिनुहोस्',
    'landing.hero.titleSub': 'विश्वसनीय ट्र्याक्टरहरूसँग',
    'landing.hero.description': 'नेपालभरिका विश्वसनीय ट्र्याक्टर मालिकहरूसँग जडान हुनुहोस्। रियल-टाइम लोकेशन निगरानी र सुरक्षित भुक्तानीसहित आफ्नो कृषि उपकरण आवश्यकताहरू बुक, ट्र्याक र व्यवस्थापन गर्नुहोस्।',
    'landing.hero.ctaBrowse': 'ट्र्याक्टरहरू हेर्नुहोस्',
    'landing.hero.ctaLearn': 'थप जान्नुहोस्',
    'landing.hero.stats.districts': 'जिल्ला',
    'landing.hero.stats.response': 'प्रतिक्रिया',
    'landing.hero.stats.support': 'सहयोग',
    'landing.stats.title': 'नेपालभरि किसानहरूलाई सेवा',
    'landing.stats.subtitle': 'कृषि समुदायहरूलाई विश्वसनीय ट्र्याक्टर सेवाहरूसँग जडान गर्दै',
    'landing.value.badge': 'किन किसानहरू हामीलाई छान्छन्',
    'landing.value.title': 'नेपालभरि कृषिलाई सशक्त बनाउँदै',
    'landing.value.subtitle': 'हामी ट्र्याक्टर मालिक र किसानहरूबीचको खाडल पटाउँछौं, सबैलाई कृषि उपकरण पहुँचयोग्य बनाउँछौं।',
    'landing.value.coverage.title': 'राष्ट्रव्यापी कभरेज',
    'landing.value.coverage.desc': 'तराई मैदानदेखि हिमाली भेगसम्म, नेपालका सबै ७७ जिल्लामा ट्र्याक्टरहरू पहुँच गर्नुहोस्।',
    'landing.value.tracking.title': 'रियल-टाइम ट्र्याकिङ',
    'landing.value.tracking.desc': 'भाडाको अवधिभर पारदर्शिता र सुरक्षा सुनिश्चित गर्दै रियल-टाइममा आफ्नो बुक गरिएको ट्र्याक्टरको स्थान निगरानी गर्नुहोस्।',
    'landing.value.secure.title': 'सुरक्षित र भरपर्दो',
    'landing.value.secure.desc': 'प्रमाणित ट्र्याक्टरहरू, सुरक्षित भुक्तानी विकल्पहरू (eSewa र COD), र शान्तिका लागि व्यापक बुकिङ व्यवस्थापन।',
    'landing.value.trusted': '१०००+ किसानहरूले विश्वास गर्छन्',
    'landing.value.community': 'बढ्दो कृषि पेशेवर समुदायमा सामेल हुनुहोस्',
    'landing.cta.titleNew': 'के तपाईं आफ्नो खेतलाई शक्ति दिन तयार हुनुहुन्छ?',
    'landing.cta.description': 'नेपालभरिका हजारौं किसानहरूसँग जडान हुनुहोस् जसले आफ्नो कृषि उपकरण आवश्यकताहरूका लागि Tractor Sewa मा विश्वास गर्छन्। आजै आफ्नो ट्र्याक्टर बुक गर्नुहोस् र निर्बाध सेवा अनुभव गर्नुहोस्।',
    'landing.cta.browse': 'उपलब्ध ट्र्याक्टरहरू हेर्नुहोस्',
    'landing.cta.createAccount': 'खाता बनाउनुहोस्',
    'landing.cta.verified': 'प्रमाणित ट्र्याक्टरहरू',
    'landing.cta.securePayments': 'सुरक्षित भुक्तानी',
    'landing.cta.realTimeTracking': 'रियल-टाइम ट्र्याकिङ',
    'landing.hero.mainTitle': 'ट्र्याक्टर बुकिङ प्रणाली',
    'landing.hero.mainSubtitle': 'रियल-टाइम दृश्यता, सुरक्षित भुक्तानी, र शक्तिशाली एडमिन उपकरणहरूसहित नेपालभरि ट्र्याक्टरहरू भाडामा लिनुहोस्, ट्र्याक गर्नुहोस् र व्यवस्थापन गर्नुहोस्।',
    'landing.hero.browseButton': 'ट्र्याक्टरहरू हेर्नुहोस्',
    'landing.hero.howItWorksButton': 'यसले कसरी काम गर्छ',
    'landing.stats.activeTractors': 'सक्रिय ट्र्याक्टरहरू',
    'landing.stats.bookingsCompleted': 'पूरा भएका बुकिङहरू',
    'landing.stats.districtsCovered': 'कभर भएका जिल्लाहरू',
    'landing.stats.avgRating': 'औसत रेटिङ',
    'landing.featured.title': 'विशेष ट्र्याक्टरहरू',
    'landing.featured.subtitle': 'तपाईंको नजिकै बुक गर्न तयार उच्च मागका मोडेलहरू।',
    'landing.featured.seeAll': 'सबै हेर्नुहोस्',
    'landing.featured.viewDetails': 'विवरण हेर्नुहोस्',
    'landing.featured.noTractors': 'अहिले कुनै ट्र्याक्टर उपलब्ध छैन।',
    'landing.featured.checkBack': 'नयाँ सूचीहरूका लागि छिट्टै फेरि जाँच गर्नुहोस्!',
    'landing.howItWorks.title': 'यसले कसरी काम गर्छ',
    'landing.howItWorks.subtitle': 'खोजदेखि भुक्तानीसम्म केही सरल चरणहरूमा।',
    'landing.howItWorks.step1.title': 'ब्राउज र फिल्टर',
    'landing.howItWorks.step1.desc': 'स्थान, मूल्य, हर्सपावर र उपलब्धताको आधारमा खोज्नुहोस्।',
    'landing.howItWorks.step2.title': 'स्लट छान्नुहोस्',
    'landing.howItWorks.step2.desc': 'तपाईंको तालिकासँग मिल्ने मिति र समय छान्नुहोस्।',
    'landing.howItWorks.step3.title': 'लाइभ ट्र्याकिङ',
    'landing.howItWorks.step3.desc': 'नक्शामा रियल-टाइममा आफ्नो ट्र्याक्टर पछ्याउनुहोस्।',
    'landing.howItWorks.step4.title': 'काममा लाग्नुहोस्',
    'landing.howItWorks.step4.desc': 'अपरेटर आउँछ र काम समयमै सुरु हुन्छ।',
    'landing.howItWorks.step5.title': 'सजिलो भुक्तानी',
    'landing.howItWorks.step5.desc': 'eSewa वा नगद डेलिभरी मार्फत सुरक्षित रूपमा भुक्तानी गर्नुहोस्।',
    'landing.whyChoose.title': 'किन Tractor Sewa छान्ने?',
    'landing.whyChoose.subtitle': 'नेपालको भू-भाग र कृषि आवश्यकताहरूका लागि निर्माण गरिएको।',
    'landing.whyChoose.feature1.title': 'रियल-टाइम ट्र्याकिङ',
    'landing.whyChoose.feature1.desc': 'प्रत्येक बुकिङका लागि लाइभ GPS ट्र्याकिङ र मार्ग दृश्यीकरण।',
    'landing.whyChoose.feature2.title': 'लचिलो भुक्तानी',
    'landing.whyChoose.feature2.desc': 'तत्काल प्रमाणीकरणसहित eSewa वा नगद डेलिभरी मार्फत भुक्तानी गर्नुहोस्।',
    'landing.whyChoose.feature3.title': 'सुरक्षित र पारदर्शी',
    'landing.whyChoose.feature3.desc': 'प्रमाणित मालिकहरू, स्पष्ट मूल्य, र सुरक्षित लेनदेन।',
    'landing.whyChoose.feature4.title': 'अनुकूलित अपरेसनहरू',
    'landing.whyChoose.feature4.desc': 'एडमिनहरूका लागि स्मार्ट लोजिस्टिक्स र उपयोग अन्तर्दृष्टिहरू।',
    'landing.cta.title': 'यस हप्ता ट्र्याक्टर चाहिन्छ?',
    'landing.cta.subtitle': 'तपाईंको क्षेत्रमा उपलब्धता जाँच गर्नुहोस् र तुरुन्त पुष्टि गर्नुहोस्। अपरेटरहरू प्रमाणित छन् र तालिका अनुसार काम गर्न तयार छन्।',
    'landing.cta.browseButton': 'ट्र्याक्टरहरू हेर्नुहोस्',
    'landing.cta.signInButton': 'साइन इन',
    // Admin Dashboard
    'admin.dashboard.title': 'एडमिन ड्यासबोर्ड',
    'admin.dashboard.subtitle': 'आफ्नो ट्र्याक्टर भाडा व्यवसाय व्यवस्थापन गर्नुहोस्',
    'admin.dashboard.stats.tractors': 'कुल ट्र्याक्टरहरू',
    'admin.dashboard.stats.available': 'उपलब्ध',
    'admin.dashboard.stats.bookings': 'कुल बुकिङहरू',
    'admin.dashboard.stats.paid': 'भुक्तानी भएको',
    'admin.dashboard.stats.revenue': 'कुल आम्दानी',
    'admin.dashboard.stats.allTime': 'सबै समय',
    'admin.dashboard.stats.users': 'सक्रिय प्रयोगकर्ताहरू',
    'admin.dashboard.stats.registered': 'दर्ता भएको',
    'admin.dashboard.actions.title': 'छिटो कार्यहरू',
    'admin.dashboard.actions.manageTractors': 'ट्र्याक्टर व्यवस्थापन',
    'admin.dashboard.actions.manageTractorsDesc': 'ट्र्याक्टरहरू थप्न, सम्पादन गर्न र हटाउन',
    'admin.dashboard.actions.manageBookings': 'बुकिङ व्यवस्थापन',
    'admin.dashboard.actions.manageBookingsDesc': 'बुकिङहरू स्वीकृत, अस्वीकृत वा प्रमाणित गर्न',
    'admin.dashboard.actions.browseTractors': 'ट्र्याक्टरहरू हेर्नुहोस्',
    'admin.dashboard.actions.browseTractorsDesc': 'आफ्नो सार्वजनिक ट्र्याक्टर क्याटलग हेर्नुहोस्',
    'admin.dashboard.actions.viewReports': 'रिपोर्टहरू हेर्नुहोस्',
    'admin.dashboard.actions.viewReportsDesc': 'अन्तर्दृष्टि र सारांशहरू प्राप्त गर्नुहोस्',
    'admin.dashboard.recent.title': 'हालैका बुकिङहरू',
    'admin.dashboard.recent.empty': 'अहिलेसम्म कुनै बुकिङ छैन',
    'admin.dashboard.recent.unknownTractor': 'अज्ञात ट्र्याक्टर',
    'admin.dashboard.recent.unknownUser': 'अज्ञात प्रयोगकर्ता',
    'admin.dashboard.loading': 'लोड भइरहेको छ...',
    'admin.dashboard.loadingData': 'ड्यासबोर्ड डेटा लोड भइरहेको छ...',
    // Login & Register
    'auth.welcome': 'फेरि स्वागत छ',
    'auth.welcomeDesc': 'जारी राख्न आफ्नो खातामा साइन इन गर्नुहोस्',
    'auth.getStarted': 'सुरु गर्नुहोस्',
    'auth.getStartedDesc': 'ट्र्याक्टर भाडामा लिन सुरु गर्न आफ्नो खाता बनाउनुहोस्',
    'auth.login.title': 'लगइन',
    'auth.login.description': 'एडमिन पहुँचका लागि admin@tbs.local वा ग्राहक पहुँचका लागि कुनै पनि इमेल प्रयोग गर्नुहोस्',
    'auth.register.title': 'साइन अप',
    'auth.register.description': 'आफ्नो खाता बनाउन आफ्नो विवरण प्रविष्ट गर्नुहोस्',
    'auth.email': 'इमेल',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड पुष्टि गर्नुहोस्',
    'auth.fullName': 'पूरा नाम',
    'auth.emailPlaceholder': 'तपाईंको@इमेल.com',
    'auth.passwordPlaceholder': 'आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्',
    'auth.passwordCreatePlaceholder': 'पासवर्ड बनाउनुहोस्',
    'auth.passwordConfirmPlaceholder': 'आफ्नो पासवर्ड पुष्टि गर्नुहोस्',
    'auth.namePlaceholder': 'तपाईंको पूरा नाम',
    'auth.signIn': 'साइन इन',
    'auth.signingIn': 'साइन इन भइरहेको छ...',
    'auth.signUp': 'साइन अप',
    'auth.dontHaveAccount': 'खाता छैन?',
    'auth.alreadyHaveAccount': 'पहिले नै खाता छ?',
    'auth.createAccount': 'खाता बनाउनुहोस्',
    'auth.creatingAccount': 'खाता बनाइरहेको छ...',
    'auth.fillAllFields': 'कृपया सबै फिल्डहरू भर्नुहोस्',
    'auth.passwordsDontMatch': 'पासवर्डहरू मेल खाँदैनन्',
    'auth.passwordMinLength': 'पासवर्ड कम्तिमा ६ वर्णको हुनुपर्छ',
    // About Page
    'about.hero.title': 'Tractor Sewa को बारेमा',
    'about.hero.subtitle': 'सुलभ प्रविधि, साझा स्रोतहरू र समुदाय-चालित नवीनताको माध्यमबाट नेपालमा कृषिलाई क्रान्तिकारी बनाउँदै।',
    'about.mission.title': 'हाम्रो मिशन',
    'about.mission.desc1': 'नेपालका सबै किसानहरूमा ट्र्याक्टर पहुँचयोग्य बनाएर नेपालमा कृषिलाई यान्त्रिकीकरण गर्नु हाम्रो मिशन हो।',
    'about.mission.desc2': 'हामी ट्र्याक्टर मालिकहरूलाई किसानहरूसँग जडान गर्छौं, न्यायोचित मूल्य र भरपर्दो सेवा सुनिश्चित गर्दै।',
    'about.vision.title': 'हाम्रो दृष्टिकोण',
    'about.vision.desc1': 'नेपालको अग्रणी कृषि प्रविधि प्लेटफर्म बन्नु, लाखौं किसानहरूलाई सुलभ, दक्ष र टिकाउ खेती समाधानहरू प्रदान गर्दै।',
    'about.vision.desc2': 'हामी भविष्यको कल्पना गर्छौं जहाँ प्रविधिले परम्परागत खेती र आधुनिक कृषि अभ्यासहरूबीचको खाडल पटाउँछ।',
    'about.values.title': 'हाम्रो मुख्य मूल्यहरू',
    'about.values.subtitle': 'हामीले गर्ने सबै कुरालाई निर्देशन गर्ने सिद्धान्तहरू',
    'about.values.trust.title': 'विश्वास र सुरक्षा',
    'about.values.trust.desc': 'प्रमाणित मालिकहरू, सुरक्षित भुक्तानी, र पारदर्शी लेनदेन।',
    'about.values.community.title': 'समुदाय प्रथम',
    'about.values.community.desc': 'किसान र ट्र्याक्टर मालिकहरूलाई समर्थन गर्ने नेटवर्क निर्माण गर्दै।',
    'about.values.innovation.title': 'नवीनता',
    'about.values.innovation.desc': 'नेपालमा कृषिलाई आधुनिकीकरण गर्न प्रविधिको उपयोग गर्दै।',
    'about.values.quality.title': 'गुणस्तरीय सेवा',
    'about.values.quality.desc': 'व्यावसायिक अपरेटर र मर्मतसहित प्रमाणित फ्लीट।',
    'about.impact.title': 'हाम्रो प्रभाव',
    'about.impact.subtitle': 'कृषिलाई रूपान्तरण गर्न हाम्रो प्रतिबद्धतालाई प्रतिबिम्बित गर्ने संख्याहरू',
    'about.impact.tractors': 'सक्रिय ट्र्याक्टरहरू',
    'about.impact.tractors.desc': 'प्रमाणित र तयार',
    'about.impact.bookings': 'बुकिङहरू',
    'about.impact.bookings.desc': 'सफलतापूर्वक पूरा भएको',
    'about.impact.districts': 'जिल्लाहरू',
    'about.impact.districts.desc': 'राष्ट्रव्यापी कभरेज',
    'about.impact.rating': 'रेटिङ',
    'about.impact.rating.desc': 'औसत प्रयोगकर्ता रेटिङ',
    'about.journey.title': 'हाम्रो यात्रा',
    'about.journey.subtitle': 'हाम्रो वृद्धिलाई आकार दिने माइलस्टोनहरू',
    'about.journey.2020': 'स्थापना',
    'about.journey.2020.desc': 'ट्र्याक्टर भाडालाई डिजिटलाइज गर्ने दृष्टिकोणसँग सुरुवात गरियो',
    'about.journey.2021': '१०० ट्र्याक्टर',
    'about.journey.2021.desc': 'हाम्रो पहिलो प्रमुख माइलस्टोन पुग्यौं',
    'about.journey.2022': '५,००० बुकिङ',
    'about.journey.2022.desc': 'नेपालभरि हजारौं किसानहरूलाई सेवा दियौं',
    'about.journey.2023': 'राष्ट्रव्यापी',
    'about.journey.2023.desc': 'नेपालका सबै ७७ जिल्लामा विस्तार गर्यौं',
    'about.journey.2024': '१०,०००+ प्रयोगकर्ता',
    'about.journey.2024.desc': 'बढ्दो किसान र मालिकहरूको समुदाय',
    'about.why.title': 'किन Tractor Sewa छान्ने?',
    'about.why.subtitle': 'कृषि प्रविधि क्षेत्रमा हामीलाई अलग बनाउने कुराहरू',
    'about.why.network.title': 'राष्ट्रव्यापी नेटवर्क',
    'about.why.network.desc': 'नेपालका सबै ७७ जिल्लामा ट्र्याक्टरहरूको पहुँच। तपाईं कुनै पनि ठाउँमा हुनुहुन्छ, तपाईंको नजिकैको उपकरण फेला पार्नुहोस्।',
    'about.why.tracking.title': 'रियल-टाइम ट्र्याकिङ',
    'about.why.tracking.desc': 'रियल-टाइममा आफ्नो ट्र्याक्टरको स्थान र मार्ग निगरानी गर्नुहोस्। आफ्नो उपकरण कहिले आउनेछ भन्ने थाहा पाउनुहोस्।',
    'about.why.verified.title': 'प्रमाणित र विश्वसनीय',
    'about.why.verified.desc': 'सबै ट्र्याक्टर र अपरेटरहरू प्रमाणित छन्। हामी गुणस्तर, विश्वसनीयता र व्यावसायिक सेवा मानकहरू सुनिश्चित गर्छौं।',
    'about.cta.title': 'हाम्रो बढ्दो समुदायमा सामेल हुनुहोस्',
    'about.cta.desc': 'तपाईं उपकरण खोजिरहनुभएको किसान हुनुहुन्छ वा कमाउन चाहनुहुन्छ ट्र्याक्टर मालिक, Tractor Sewa तपाईंलाई जडान गर्न यहाँ छ।',
    'about.cta.browse': 'ट्र्याक्टरहरू हेर्नुहोस्',
    'about.cta.contact': 'हामीलाई सम्पर्क गर्नुहोस्',
    // Contact Page
    'contact.hero.title': 'सम्पर्क गर्नुहोस्',
    'contact.hero.subtitle': 'प्रश्नहरू छन्? हामी यहाँ मद्दत गर्नका लागि छौं। हामीलाई सम्पर्क गर्नुहोस् र हामी यथाशीघ्र जवाफ दिनेछौं।',
    'contact.getInTouch': 'सम्पर्क गर्नुहोस्',
    'contact.getInTouch.desc': 'ट्र्याक्टर बुक गर्ने वा आफ्नो वाहन सूचीबद्ध गर्ने बारे प्रश्नहरू छन्? हाम्रो टोली तपाईंलाई सहयोग गर्न तयार छ।',
    'contact.phone': 'फोन',
    'contact.phone.number': '+९७७ ९८००००००००',
    'contact.phone.hours': 'सोम-शुक्र: ८ बजे - ५ बजे',
    'contact.email': 'इमेल',
    'contact.email.address': 'info@tractorsewa.com',
    'contact.email.support': '२४/७ समर्थन',
    'contact.address': 'ठेगाना',
    'contact.address.location': 'काठमाडौं, नेपाल',
    'contact.address.visit': 'हाम्रो कार्यालयमा भ्रमण गर्नुहोस्',
    'contact.form.title': 'हामीलाई सन्देश पठाउनुहोस्',
    'contact.form.subtitle': 'तलको फर्म भर्नुहोस् र हामी २४ घण्टाभित्र तपाईंसँग सम्पर्क गर्नेछौं।',
    'contact.form.firstName': 'पहिलो नाम *',
    'contact.form.lastName': 'अन्तिम नाम *',
    'contact.form.email': 'इमेल *',
    'contact.form.phone': 'फोन',
    'contact.form.subject': 'विषय *',
    'contact.form.subject.placeholder': 'यो कसको बारेमा हो?',
    'contact.form.message': 'सन्देश *',
    'contact.form.message.placeholder': 'हामीले तपाईंलाई कसरी मद्दत गर्न सक्छौं भन्नुहोस्...',
    'contact.form.send': 'सन्देश पठाउनुहोस्',
    'contact.form.sending': 'पठाइरहेको छ...',
    'contact.form.success': 'सन्देश सफलतापूर्वक पठाइयो! हामी छिट्टै तपाईंसँग सम्पर्क गर्नेछौं।',
    'contact.hours.title': 'व्यापारिक समय',
    'contact.hours.weekday': 'सोमबार - शुक्रबार',
    'contact.hours.weekday.time': '८:०० बिहान - ५:०० बेलुका',
    'contact.hours.saturday': 'शनिबार',
    'contact.hours.saturday.time': '९:०० बिहान - २:०० बेलुका',
    'contact.hours.sunday': 'आइतबार',
    'contact.hours.sunday.time': 'बन्द',
    'contact.hours.email24': 'इमेल समर्थन २४/७ उपलब्ध',
    'contact.faq.title': 'बारम्बार सोधिने प्रश्नहरू',
    'contact.faq.q1': 'मैले कसरी ट्र्याक्टर बुक गर्ने?',
    'contact.faq.a1': 'सरलतापूर्वक हाम्रो उपलब्ध ट्र्याक्टरहरू हेर्नुहोस्, आफ्नो मनपर्ने मिति र समय छान्नुहोस्, र बुकिङ पूरा गर्नुहोस्। तपाईं eSewa वा नगद डेलिभरी मार्फत भुक्तानी गर्न सक्नुहुन्छ।',
    'contact.faq.q2': 'तपाईंले कुन क्षेत्रहरू कभर गर्नुहुन्छ?',
    'contact.faq.a2': 'हामी नेपालका सबै ७७ जिल्लामा सञ्चालन गर्छौं। तपाईंको नजिकैको ट्र्याक्टर फेला पार्न हाम्रो स्थान फिल्टर प्रयोग गर्नुहोस्।',
    'contact.faq.q3': 'मैले आफ्नो ट्र्याक्टर कसरी सूचीबद्ध गर्ने?',
    'contact.faq.a3': 'यो फर्म मार्फत वा info@tractorsewa.com मा इमेल गरेर हामीलाई सम्पर्क गर्नुहोस्। हाम्रो टोलीले तपाईंलाई दर्ता प्रक्रियामा मार्गदर्शन गर्नेछ।',
    'contact.faq.q4': 'कुन भुक्तानी विधिहरू स्वीकार गरिन्छ?',
    'contact.faq.a4': 'हामी अनलाइन भुक्तानीका लागि eSewa र तपाईंको सुविधाका लागि नगद डेलिभरी स्वीकार गर्छौं।',
    'contact.help.title': 'हामी मद्दत गर्न यहाँ छौं',
    'contact.help.desc': 'हाम्रो समर्थन टोली तपाईंलाई उत्तम सम्भावित सेवा प्रदान गर्न प्रतिबद्ध छ। बुकिङ, प्राविधिक सहायता, वा हामीसँग साझेदारी गर्न चाहनुहुन्छ भने, हामी सन्देशको लागि मात्र टाढा छौं।',
    'contact.help.response': 'औसत प्रतिक्रिया समय:',
    'contact.help.response.time': '२ घण्टा भित्र',
    'contact.help.languages': 'समर्थन भाषाहरू:',
    'contact.help.languages.list': 'अङ्ग्रेजी र नेपाली',
    // Privacy Page
    'privacy.hero.title': 'गोपनीयता नीति',
    'privacy.hero.subtitle': 'तपाईंको गोपनीयता हाम्रो लागि महत्त्वपूर्ण छ। यो नीतिले हामीले कसरी तपाईंको व्यक्तिगत जानकारी सङ्कलन, प्रयोग र सुरक्षा गर्छौं भन्ने कुरा बताउँछ।',
    'privacy.hero.lastUpdated': 'अन्तिम अपडेट:',
    'privacy.hero.effectiveDate': 'प्रभावकारी मिति:',
    'privacy.hero.december2024': 'डिसेम्बर २०२४',
    'privacy.hero.january2024': 'जनवरी १, २०२४',
    'privacy.summary.title': 'छिटो सारांश',
    'privacy.summary.p1': 'हामीले हाम्रो सेवाहरू प्रदान गर्न आवश्यक जानकारी मात्र सङ्कलन गर्छौं',
    'privacy.summary.p2': 'तपाईंको डेटा इन्क्रिप्टेड र सुरक्षित रूपमा भण्डारण गरिन्छ',
    'privacy.summary.p3': 'हामीले कहिल्यै तपाईंको व्यक्तिगत जानकारी तेस्रो पक्षलाई बेच्दैनौं',
    'privacy.summary.p4': 'तपाईंसँग आफ्नो डेटामा पूर्ण नियन्त्रण छ र कुनै पनि समयमा मेटाउने अनुरोध गर्न सक्नुहुन्छ',
    'privacy.section.collection.title': 'जानकारी सङ्कलन',
    'privacy.section.collection.p1': 'हामीले तपाईंले सिधै प्रदान गर्नुभएको जानकारी सङ्कलन गर्छौं जब तपाईं:',
    'privacy.section.collection.p2': '• हाम्रो प्लेटफर्ममा खाता वा प्रोफाइल बनाउनुहुन्छ',
    'privacy.section.collection.p3': '• ट्र्याक्टर बुक गर्नुहुन्छ वा आफ्नो उपकरण सूचीबद्ध गर्नुहुन्छ',
    'privacy.section.collection.p4': '• ग्राहक सहयोगका लागि हामीलाई सम्पर्क गर्नुहुन्छ',
    'privacy.section.collection.p5': '• हाम्रो न्युजलेटर वा विपणन सञ्चारहरूमा सदस्यता लिनुहुन्छ',
    'privacy.section.collection.p6': '• सर्वेक्षण वा प्रचार गतिविधिहरूमा सहभागी हुनुहुन्छ',
    'privacy.section.collection.p7': '',
    'privacy.section.collection.p8': 'यो जानकारीमा समावेश हुन सक्छ:',
    'privacy.section.collection.p9': '• व्यक्तिगत पहिचान (नाम, इमेल, फोन नम्बर)',
    'privacy.section.collection.p10': '• सेवा वितरणका लागि स्थान डेटा',
    'privacy.section.collection.p11': '• भुक्तानी जानकारी (तेस्रो-पक्ष प्रदायकहरू मार्फत सुरक्षित रूपमा प्रशोधन गरिन्छ)',
    'privacy.section.collection.p12': '• प्रोफाइल तस्बिरहरू र खाता प्राथमिकताहरू',
    'privacy.section.collection.p13': '• सञ्चार इतिहास र सहयोग टिकटहरू',
    'privacy.section.use.title': 'जानकारीको प्रयोग',
    'privacy.section.use.p1': 'हामीले सङ्कलन गरेको जानकारी प्रयोग गर्छौं:',
    'privacy.section.use.p2': '• हाम्रो सेवाहरू प्रदान, राख्न र सुधार गर्न',
    'privacy.section.use.p3': '• लेनदेन प्रशोधन र बुकिङ व्यवस्थापन गर्न',
    'privacy.section.use.p4': '• बुकिङ पुष्टिकरण, अपडेट र सूचनाहरू पठाउन',
    'privacy.section.use.p5': '• प्रयोगकर्ता पहिचान प्रमाणीकरण र धोका रोकथाम गर्न',
    'privacy.section.use.p6': '• ग्राहक सेवा अनुरोधहरूको जवाफ दिन',
    'privacy.section.use.p7': '• प्रयोगकर्ता अनुभव बढाउन प्रयोग प्याटर्नहरू विश्लेषण गर्न',
    'privacy.section.use.p8': '• विपणन सञ्चार पठाउन (तपाईंको सहमतिसहित)',
    'privacy.section.use.p9': '• कानुनी दायित्वहरू पूरा गर्न र हाम्रो सर्तहरू लागू गर्न',
    'privacy.section.use.p10': '',
    'privacy.section.use.p11': 'हामीले तपाईंको व्यक्तिगत जानकारी तेस्रो पक्षलाई बेच्दैनौं।',
    'privacy.section.security.title': 'डेटा सुरक्षा',
    'privacy.section.security.p1': 'हामीले तपाईंको डेटा सुरक्षा गर्न व्यापक सुरक्षा उपायहरू लागू गर्छौं:',
    'privacy.section.security.p2': '• डेटा प्रसारणका लागि उद्योग-मानक इन्क्रिप्सन (SSL/TLS)',
    'privacy.section.security.p3': '• सुरक्षित पासवर्ड ह्यासिङ र प्रमाणीकरण प्रोटोकलहरू',
    'privacy.section.security.p4': '• नियमित सुरक्षा अडिटहरू र भेद्यता मूल्याङ्कनहरू',
    'privacy.section.security.p5': '• पहुँच नियन्त्रणहरू र डेटा सुरक्षामा कर्मचारी प्रशिक्षण',
    'privacy.section.security.p6': '• प्रमाणित प्रदायकहरू मार्फत सुरक्षित भुक्तानी प्रशोधन',
    'privacy.section.security.p7': '',
    'privacy.section.security.p8': 'जबकि हामीले तपाईंको जानकारी सुरक्षा गर्न प्रयास गर्छौं, इन्टरनेट मार्फत प्रसारणको कुनै पनि विधि १००% सुरक्षित छैन। हामी पूर्ण सुरक्षा ग्यारेन्टी दिन सक्दैनौं तर उच्चतम मानकहरू कायम राख्न प्रतिबद्ध छौं।',
    'privacy.section.storage.title': 'डेटा भण्डारण र अवधारण',
    'privacy.section.storage.p1': 'डेटा भण्डारण:',
    'privacy.section.storage.p2': '• तपाईंको डेटा उचित सुरक्षा उपायहरूसहित सुरक्षित सर्भरहरूमा भण्डारण गरिन्छ',
    'privacy.section.storage.p3': '• हामी अन्तर्राष्ट्रिय सुरक्षा मानकहरू पालना गर्ने प्रतिष्ठित क्लाउड सेवा प्रदायकहरू प्रयोग गर्छौं',
    'privacy.section.storage.p4': '',
    'privacy.section.storage.p5': 'डेटा अवधारण:',
    'privacy.section.storage.p6': '• खाता जानकारी: तपाईंको खाता सक्रिय रहँदासम्म राखिन्छ',
    'privacy.section.storage.p7': '• बुकिङ रेकर्डहरू: कानुनी र लेखा उद्देश्यहरूका लागि ७ वर्ष सम्म राखिन्छ',
    'privacy.section.storage.p8': '• विपणन डेटा: तपाईंले सदस्यता रद्द नगरेसम्म राखिन्छ',
    'privacy.section.storage.p9': '• सहयोग सञ्चार: ३ वर्ष सम्म राखिन्छ',
    'privacy.section.storage.p10': '',
    'privacy.section.storage.p11': 'तपाईंले कुनै पनि समयमा आफ्नो डेटा मेटाउने अनुरोध गर्न सक्नुहुन्छ, कानुनी आवश्यकताहरूको अधीनमा।',
    'privacy.section.rights.title': 'तपाईंको अधिकारहरू',
    'privacy.section.rights.p1': 'तपाईंसँग अधिकार छ:',
    'privacy.section.rights.p2': '• आफ्नो व्यक्तिगत डेटामा पहुँच',
    'privacy.section.rights.p3': '• गलत वा अपूर्ण जानकारी सुधार गर्न',
    'privacy.section.rights.p4': '• आफ्नो डेटा मेटाउने अनुरोध गर्न (भुल्ने अधिकार)',
    'privacy.section.rights.p5': '• आफ्नो डेटाको प्रशोधनमा असहमति जनाउन',
    'privacy.section.rights.p6': '• डेटा पोर्टेबिलिटी अनुरोध गर्न',
    'privacy.section.rights.p7': '• विपणन सञ्चारका लागि सहमति फिर्ता लिन',
    'privacy.section.rights.p8': '• सम्बन्धित डेटा सुरक्षा अधिकारीहरूसँग शिकायत दर्ज गर्न',
    'privacy.section.rights.p9': '',
    'privacy.section.rights.p10': 'यी अधिकारहरू प्रयोग गर्न, privacy@tractorsewa.com मा हामीलाई सम्पर्क गर्नुहोस्',
    'privacy.section.thirdparty.title': 'तेस्रो-पक्ष सेवाहरू',
    'privacy.section.thirdparty.p1': 'हामीले तेस्रो-पक्ष सेवाहरू प्रयोग गर्न सक्छौं जसले तपाईंको जानकारीमा पहुँच छ:',
    'privacy.section.thirdparty.p2': '• लेनदेन प्रशोधनका लागि भुक्तानी प्रशोधकहरू (eSewa, आदि)',
    'privacy.section.thirdparty.p3': '• डेटा भण्डारणका लागि क्लाउड होस्टिङ प्रदायकहरू',
    'privacy.section.thirdparty.p4': '• प्लेटफर्म प्रयोग बुझ्नका लागि विश्लेषण सेवाहरू',
    'privacy.section.thirdparty.p5': '• सञ्चारका लागि इमेल सेवा प्रदायकहरू',
    'privacy.section.thirdparty.p6': '• स्थान सुविधाहरूका लागि नक्शा सेवाहरू',
    'privacy.section.thirdparty.p7': '',
    'privacy.section.thirdparty.p8': 'यी सेवाहरू आफ्नै गोपनीयता नीतिहरू र सुरक्षा मानकहरूबाट बाध्य छन्। हामीले उनीहरूले आफ्नो सेवाहरू प्रदान गर्न आवश्यक जानकारी मात्र साझेदारी गर्छौं।',
    'privacy.section.cookies.title': 'कुकीहरू र ट्र्याकिङ',
    'privacy.section.cookies.p1': 'हामीले कुकीहरू र समान प्रविधिहरू प्रयोग गर्छौं:',
    'privacy.section.cookies.p2': '• आफ्नो सत्र र लगइन स्थिति राख्न',
    'privacy.section.cookies.p3': '• आफ्नो प्राथमिकताहरू र सेटिङहरू सम्झन',
    'privacy.section.cookies.p4': '• वेबसाइट ट्राफिक र प्रयोग प्याटर्नहरू विश्लेषण गर्न',
    'privacy.section.cookies.p5': '• व्यक्तिगत सामग्री र विज्ञापनहरू प्रदान गर्न',
    'privacy.section.cookies.p6': '',
    'privacy.section.cookies.p7': 'तपाईंले आफ्नो ब्राउजर सेटिङहरू मार्फत कुकीहरू नियन्त्रण गर्न सक्नुहुन्छ। यद्यपि, कुकीहरू असक्षम गर्दा प्लेटफर्म कार्यक्षमतामा असर पर्न सक्छ।',
    'privacy.section.children.title': 'बच्चाहरूको गोपनीयता',
    'privacy.section.children.p1': 'हाम्रो सेवाहरू १८ वर्ष मुनिका व्यक्तिहरूका लागि उद्देशित छैनन्। हामीले जानाजानी बच्चाहरूबाट व्यक्तिगत जानकारी सङ्कलन गर्दैनौं।',
    'privacy.section.children.p2': '',
    'privacy.section.children.p3': 'यदि तपाईंले विश्वास गर्नुहुन्छ कि हामीले बच्चाबाट जानकारी सङ्कलन गरेका छौं, कृपया तुरुन्त हामीलाई सम्पर्क गर्नुहोस्, र हामीले यस्तो जानकारी मेटाउने कदमहरू चाल्नेछौं।',
    'privacy.changes.title': 'यस नीतिमा परिवर्तनहरू',
    'privacy.changes.p1': 'हामीले हाम्रो अभ्यासहरूमा परिवर्तनहरू वा कानुनी, अपरेसनल, वा नियामक कारणहरूका लागि समय-समयमा यो गोपनीयता नीति अपडेट गर्न सक्छौं। हामीले तपाईंलाई कुनै पनि महत्त्वपूर्ण परिवर्तनहरूको बारेमा सूचना दिनेछौं:',
    'privacy.changes.p2': '• नयाँ "अन्तिम अपडेट" मितिसहित यस पृष्ठमा अपडेट गरिएको नीति पोस्ट गरेर',
    'privacy.changes.p3': '• दर्ता भएका प्रयोगकर्ताहरूलाई इमेल सूचना पठाएर',
    'privacy.changes.p4': '• हाम्रो प्लेटफर्ममा प्रमुख सूचना प्रदर्शन गरेर',
    'privacy.changes.p5': '',
    'privacy.changes.p6': 'परिवर्तनहरू प्रभावकारी भएपछि हाम्रो सेवाहरूको निरन्तर प्रयोगले अपडेट गरिएको नीतिको स्वीकृतिलाई जनाउँछ।',
    'privacy.contact.title': 'गोपनीयताको बारेमा प्रश्नहरू?',
    'privacy.contact.desc': 'यदि तपाईंसँग यस गोपनीयता नीति वा हाम्रो डेटा अभ्यासहरूको बारेमा कुनै प्रश्न, चिन्ता, वा अनुरोधहरू छन् भने, कृपया हामीलाई सम्पर्क गर्न नहिचकिचाउनुहोस्।',
    'privacy.contact.email1': 'privacy@tractorsewa.com',
    'privacy.contact.email2': 'info@tractorsewa.com',
    'privacy.contact.button': 'हामीलाई सम्पर्क गर्नुहोस्',
    // User Dashboard
    'dashboard.title': 'मेरो ड्यासबोर्ड',
    'dashboard.welcome': 'फेरि स्वागत छ',
    'dashboard.stats.totalBookings': 'कुल बुकिङहरू',
    'dashboard.stats.activeBookings': 'सक्रिय बुकिङहरू',
    'dashboard.stats.totalSpent': 'कुल खर्च',
    'dashboard.myBookings': 'मेरो बुकिङहरू',
    'dashboard.empty.title': 'अहिलेसम्म कुनै बुकिङ छैन',
    'dashboard.empty.subtitle': 'ट्र्याक्टरहरू ब्राउज गरेर सुरु गर्नुहोस्',
    'dashboard.loading': 'लोड भइरहेको छ...',
    // Profile
    'profile.title': 'मेरो प्रोफाइल',
    'profile.subtitle': 'आफ्नो खाता जानकारी व्यवस्थापन गर्नुहोस्',
    'profile.information': 'प्रोफाइल जानकारी',
    'profile.fullName': 'पूरा नाम',
    'profile.emailAddress': 'इमेल ठेगाना',
    'profile.emailCannotChange': 'इमेल परिवर्तन गर्न सकिँदैन',
    'profile.editProfile': 'प्रोफाइल सम्पादन गर्नुहोस्',
    'profile.saveChanges': 'परिवर्तनहरू बचत गर्नुहोस्',
    'profile.saving': 'बचत भइरहेको छ...',
    'profile.cancel': 'रद्द गर्नुहोस्',
    'profile.uploading': 'अपलोड भइरहेको छ...',
    'profile.enterName': 'आफ्नो नाम प्रविष्ट गर्नुहोस्',
    // Tracking
    'tracking.title': 'रियल-टाइम ट्र्याक्टर ट्र्याकिङ',
    'tracking.subtitle': 'तपाईंको स्वीकृत बुकिङहरूका लागि लाइभ मार्ग, ETA र डेलिभरी प्रगति हेर्नुहोस्।',
    'tracking.selectBooking': 'बुकिङ छान्नुहोस्',
    'tracking.noBookings': 'तपाईंसँग अहिले ट्र्याकिङका लागि कुनै बुकिङ छैन। एकपटक ट्र्याक्टर स्वीकृत भएपछि, यसको मार्ग यहाँ देखिनेछ।',
    'tracking.loading': 'लोड भइरहेको छ...',
    // Payment
    'payment.success.title': 'भुक्तानी सफल!',
    'payment.success.verifying': 'भुक्तानी प्रमाणीकरण गर्दै...',
    'payment.success.confirmed': 'तपाईंको बुकिङ पुष्टि भएको छ। तपाईंलाई छिट्टै ड्यासबोर्डमा पुन: निर्देशन गरिनेछ।',
    'payment.success.goDashboard': 'ड्यासबोर्डमा जानुहोस्',
    'payment.failure.title': 'भुक्तानी असफल',
    'payment.failure.withBooking': 'तपाईंको बुकिङ सिर्जना भएको छ तर भुक्तानी प्रशोधन गर्न सकिएन। कृपया पुन: प्रयास गर्नुहोस् वा नगद डेलिभरी प्रयोग गर्नुहोस्।',
    'payment.failure.withoutBooking': 'तपाईंको भुक्तानी प्रशोधन गर्न सकिएन। कृपया पुन: प्रयास गर्नुहोस्।',
    'payment.failure.goDashboard': 'ड्यासबोर्डमा जानुहोस्',
    'payment.invalidBookingId': 'अवैध बुकिङ ID',
    'payment.verified': 'भुक्तानी सफलतापूर्वक प्रमाणित भयो!',
    'payment.verificationFailed': 'भुक्तानी प्रमाणीकरण असफल',
    // NotFound
    'notfound.title': '४०४',
    'notfound.message': 'ओह! पृष्ठ फेला परेन',
    'notfound.returnHome': 'गृहपृष्ठमा फर्कनुहोस्',
    // MapPreview
    'mappreview.title': 'Leaflet नक्शा पूर्वावलोकन',
    'mappreview.description': 'तपाईंको वातावरणमा Leaflet टाइलहरू सही रूपमा लोड हुन्छ भन्ने पुष्टि गर्न यो पृष्ठ प्रयोग गर्नुहोस्।',
    // Common
    'common.loading': 'लोड भइरहेको छ...',
    'common.welcomeBack': 'फेरि स्वागत छ',
    'dashboard.status.confirmed': 'पुष्टि भएको',
    'dashboard.status.pending': 'बाँकी',
    'dashboard.status.completed': 'पूरा भएको',
    'dashboard.status.cancelled': 'रद्द भएको',
    'dashboard.status.refund_requested': 'रिफन्ड अनुरोध',
    'dashboard.payment.paid': 'भुक्तानी भएको',
    'dashboard.payment.pending': 'भुक्तानी बाँकी',
    'dashboard.payment.failed': 'भुक्तानी असफल',
    'dashboard.cancellation.success': 'रद्दीकरण अनुरोध पेश गरियो',
    'dashboard.cancellation.failed': 'बुकिङ रद्द गर्न असफल',
    'dashboard.totalAmount': 'कुल रकम',
    'dashboard.cancelBooking': 'बुकिङ रद्द गर्नुहोस्',
    'dashboard.trackTractor': 'ट्र्याक्टर ट्र्याक गर्नुहोस्',
    'dashboard.cancelDialog.title': 'बुकिङ रद्द गर्नुहोस्',
    'dashboard.cancelDialog.description.paid': 'के तपाईं यो बुकिङको लागि रिफन्ड अनुरोध गर्न चाहनुहुन्छ? तपाईंको रिफन्डबाट ३% शुल्क कटौती गरिनेछ। यो अनुरोध एडमिनले समीक्षा गर्नेछ।',
    'dashboard.cancelDialog.description.unpaid': 'के तपाईं यो बुकिङ रद्द गर्न निश्चित हुनुहुन्छ? यो कार्य फिर्ता गर्न सकिँदैन।',
    'dashboard.cancelDialog.cancel': 'रद्द गर्नुहोस्',
    'dashboard.cancelDialog.confirm': 'पुष्टि गर्नुहोस्',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('tbs-language') as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('tbs-language', language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string) => {
      const dictionary = translations[language];
      return dictionary[key] || translations.en[key] || key;
    };

    const toggleLanguage = () => {
      setLanguage(prev => (prev === 'en' ? 'ne' : 'en'));
    };

    return {
      language,
      setLanguage,
      toggleLanguage,
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
